'use client';

import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'mr' | 'ta' | 'te' | 'kn' | 'bn' | 'pa' | 'gu';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  // A t function that can handle placeholders
  t: (key: string, values?: {[key: string]: string | number}) => string;
}

const translations = {
  en: {
    // General
    welcome: 'Welcome',
    settings: 'Settings',
    language: 'Language',
    post: 'Post',
    // Header
    home: 'Home',
    ai_assistant: 'AI Assistant',
    market: 'Market',
    community: 'Community',
    profile: 'Profile',
    // Home Page
    welcome_to_kisanai: 'Welcome to KisanAI',
    welcome_message: 'Welcome, {{name}}!',
    smart_farming_partner: 'Your smart farming partner for a richer harvest.',
    quick_actions: 'Quick Actions',
    quick_links: 'Quick Links',
    get_farming_advice: 'Get farming advice',
    market_prices: 'Market Prices',
    check_crop_prices: 'Check crop prices',
    connect_with_farmers: 'Connect with farmers',
    customize_your_app: 'Customize your app',
    daily_tip: 'Daily Tip',
    daily_tip_content: 'Check soil moisture before irrigating your fields. Over-watering can be as harmful as under-watering.',
    voice_assistant: 'Voice Assistant',
    // Weather Card
    current_weather: 'Current Weather',
    weather_forecast: 'Weather Forecast',
    today: 'Today',
    weather_error: 'Weather Error',
    humidity: 'Humidity',
    wind: 'Wind',
    location_access_denied: 'Location Access Denied',
    fallback_location_weather: 'Falling back to default location for weather.',
    // Market Page
    latest_prices: 'Latest agricultural commodity prices from various markets.',
    showing_markets_near: 'Showing markets near',
    crop: 'Crop',
    price_per_unit: 'Price (per unit)',
    trend: 'Trend',
    last_updated: 'Last Updated',
    // Community Page
    community_feed: 'Community Feed',
    create_a_post: 'Create a Post',
    whats_on_your_mind: "What's on your mind, farmer?",
    // Profile Page
    login_or_signup: 'Login or Sign Up',
    enter_mobile_for_otp: 'Enter your mobile number to receive an OTP.',
    full_name: 'Full Name',
    enter_full_name: 'Enter your full name',
    mobile_number: 'Mobile Number',
    enter_mobile_number: 'Enter your 10-digit mobile number',
    send_otp: 'Send OTP',
    my_profile: 'My Profile',
    view_manage_account: 'View and manage your account details.',
    name: 'Name',
    log_out: 'Log Out',
    // Settings Page
    choose_language: 'Choose your preferred language for the app.',
    notifications: 'Notifications',
    enable_notifications: 'Enable notifications for important alerts.',
    enable_notifications_button: 'Enable Notifications',
    // Assistant Page
    ai_farming_assistant: 'AI Farming Assistant',
    ask_me_anything: 'Ask me anything about farming!',
    ask_about_crops: 'Ask about crops, soil, or pests...',
    assistant_can_mistake: 'KisanAI can make mistakes. Consider checking important information.',
    // Voice Assistant
    voice_assistant_title: 'Voice Assistant',
    listening: 'Listening...',
    processing: 'Processing...',
    ask_a_question: 'Ask a question about farming',
  },
  hi: {
    // General
    welcome: 'स्वागत है',
    settings: 'सेटिंग्स',
    language: 'भाषा',
    post: 'पोस्ट करें',
    // Header
    home: 'होम',
    ai_assistant: 'एआई सहायक',
    market: 'बाजार',
    community: 'समुदाय',
    profile: 'प्रोफ़ाइल',
    // Home Page
    welcome_to_kisanai: 'किसान-एआई में आपका स्वागत है',
    welcome_message: 'नमस्ते, {{name}}!',
    smart_farming_partner: 'एक समृद्ध फसल के लिए आपका स्मार्ट खेती पार्टनर।',
    quick_actions: 'त्वरित कार्रवाइयां',
    quick_links: 'त्वरित लिंक',
    get_farming_advice: 'खेती की सलाह लें',
    market_prices: 'बाजार मूल्य',
    check_crop_prices: 'फसलों की कीमतें जांचें',
    connect_with_farmers: 'किसानों से जुड़ें',
    customize_your_app: 'अपने ऐप को कस्टमाइज़ करें',
    daily_tip: 'आज का सुझाव',
    daily_tip_content: 'अपने खेतों की सिंचाई करने से पहले मिट्टी की नमी की जाँच करें। ज़्यादा पानी देना भी कम पानी देने जितना ही हानिकारक हो सकता है।',
    voice_assistant: 'आवाज सहायक',
    // Weather Card
    current_weather: 'वर्तमान मौसम',
    weather_forecast: 'मौसम पूर्वानुमान',
    today: 'आज',
    weather_error: 'मौसम त्रुटि',
    humidity: 'नमी',
    wind: 'हवा',
    location_access_denied: 'स्थान पहुंच अस्वीकृत',
    fallback_location_weather: 'मौसम के लिए डिफ़ॉल्ट स्थान पर वापस जा रहे हैं।',
    // Market Page
    latest_prices: 'विभिन्न बाजारों से नवीनतम कृषि जिंसों की कीमतें।',
    showing_markets_near: 'के पास के बाजार दिखा रहा है',
    crop: 'फसल',
    price_per_unit: 'मूल्य (प्रति यूनिट)',
    trend: 'प्रवृत्ति',
    last_updated: 'पिछला अपडेट',
    // Community Page
    community_feed: 'सामुदायिक फ़ीड',
    create_a_post: 'एक पोस्ट बनाएं',
    whats_on_your_mind: 'आपके मन में क्या है, किसान?',
    // Profile Page
    login_or_signup: 'लॉग इन करें या साइन अप करें',
    enter_mobile_for_otp: 'ओटीपी प्राप्त करने के लिए अपना मोबाइल नंबर दर्ज करें।',
    full_name: 'पूरा नाम',
    enter_full_name: 'अपना पूरा नाम दर्ज करें',
    mobile_number: 'मोबाइल नंबर',
    enter_mobile_number: 'अपना 10 अंकों का मोबाइल नंबर दर्ज करें',
    send_otp: 'ओटीपी भेजें',
    my_profile: 'मेरी प्रोफ़ाइल',
    view_manage_account: 'अपने खाते का विवरण देखें और प्रबंधित करें।',
    name: 'नाम',
    log_out: 'लॉग आउट',
    // Settings Page
    choose_language: 'ऐप के लिए अपनी पसंदीदा भाषा चुनें।',
    notifications: 'सूचनाएं',
    enable_notifications: 'महत्वपूर्ण सूचनाओं के लिए सूचनाएं सक्षम करें।',
    enable_notifications_button: 'सूचनाएं सक्षम करें',
    // Assistant Page
    ai_farming_assistant: 'एआई खेती सहायक',
    ask_me_anything: 'मुझसे खेती के बारे में कुछ भी पूछें!',
    ask_about_crops: 'फसलों, मिट्टी, या कीटों के बारे में पूछें...',
    assistant_can_mistake: 'किसान-एआई गलतियाँ कर सकता है। महत्वपूर्ण जानकारी की जाँच करने पर विचार करें।',
    // Voice Assistant
    voice_assistant_title: 'आवाज सहायक',
    listening: 'सुन रहा हूँ...',
    processing: 'संसाधित हो रहा है...',
    ask_a_question: 'खेती के बारे में एक प्रश्न पूछें',
  },
  mr: {
    // General
    welcome: 'स्वागत आहे',
    settings: 'सेटिंग्ज',
    language: 'भाषा',
    post: 'पोस्ट करा',
    // Header
    home: 'होम',
    ai_assistant: 'एआय सहाय्यक',
    market: 'बाजार',
    community: 'समुदाय',
    profile: 'प्रोफाइल',
    // Home Page
    welcome_to_kisanai: 'किसान-एआय मध्ये आपले स्वागत आहे',
    welcome_message: 'नमस्कार, {{name}}!',
    smart_farming_partner: 'अधिक समृद्ध पिकासाठी तुमचा स्मार्ट शेती भागीदार.',
    quick_actions: 'द्रुत क्रिया',
    quick_links: 'द्रुत दुवे',
    get_farming_advice: 'शेतीविषयक सल्ला मिळवा',
    market_prices: 'बाजारभाव',
    check_crop_prices: 'पिकांच्या किमती तपासा',
    connect_with_farmers: 'शेतकऱ्यांशी संपर्क साधा',
    customize_your_app: 'तुमचे ॲप सानुकूलित करा',
    daily_tip: 'आजचा सल्ला',
    daily_tip_content: 'आपल्या शेतात सिंचन करण्यापूर्वी जमिनीतील ओलावा तपासा. जास्त पाणी देणे हे कमी पाणी देण्याइतकेच हानिकारक असू शकते.',
    voice_assistant: 'आवाज सहाय्यक',
    // Weather Card
    current_weather: 'सध्याचे हवामान',
    weather_forecast: 'हवामान अंदाज',
    today: 'आज',
    weather_error: 'हवामान त्रुटी',
    humidity: 'आर्द्रता',
    wind: 'वारा',
    location_access_denied: 'स्थान प्रवेश नाकारला',
    fallback_location_weather: 'हवामानासाठी डीफॉल्ट स्थानावर परत जात आहे.',
    // Market Page
    latest_prices: 'विविध बाजारांतील नवीनतम कृषी मालाच्या किमती.',
    showing_markets_near: 'जवळपासची बाजारपेठ दाखवत आहे',
    crop: 'पीक',
    price_per_unit: 'किंमत (प्रति युनिट)',
    trend: 'कल',
    last_updated: 'शेवटचे अद्यतन',
    // Community Page
    community_feed: 'कम्युनिटी फीड',
    create_a_post: 'पोस्ट तयार करा',
    whats_on_your_mind: 'तुमच्या मनात काय आहे, शेतकरी?',
    // Profile Page
    login_or_signup: 'लॉगिन करा किंवा साइन अप करा',
    enter_mobile_for_otp: 'OTP मिळवण्यासाठी तुमचा मोबाईल नंबर टाका.',
    full_name: 'पूर्ण नाव',
    enter_full_name: 'तुमचे पूर्ण नाव टाका',
    mobile_number: 'मोबाईल नंबर',
    enter_mobile_number: 'तुमचा १०-अंकी मोबाईल नंबर टाका',
    send_otp: 'ओटीपी पाठवा',
    my_profile: 'माझे प्रोफाइल',
    view_manage_account: 'तुमच्या खात्याचे तपशील पहा आणि व्यवस्थापित करा.',
    name: 'नाव',
    log_out: 'लॉग आउट',
    // Settings Page
    choose_language: 'ॲपसाठी तुमची पसंतीची भाषा निवडा.',
    notifications: 'सूचना',
    enable_notifications: 'महत्वाच्या सूचनांसाठी सूचना सक्षम करा.',
    enable_notifications_button: 'सूचना सक्षम करा',
    // Assistant Page
    ai_farming_assistant: 'एआय शेती सहाय्यक',
    ask_me_anything: 'मला शेतीबद्दल काहीही विचारा!',
    ask_about_crops: 'पिके, माती किंवा कीटकांबद्दल विचारा...',
    assistant_can_mistake: 'किसान-एआय चुका करू शकतो. महत्त्वाची माहिती तपासण्याचा विचार करा.',
    // Voice Assistant
    voice_assistant_title: 'आवाज सहाय्यक',
    listening: 'ऐकत आहे...',
    processing: 'प्रક્રિયા होत आहे...',
    ask_a_question: 'शेतीबद्दल प्रश्न विचारा',
  },
  ta: {
    welcome: 'வரவேற்பு',
    settings: 'அமைப்புகள்',
    language: 'மொழி',
    post: 'பதிவு செய்',
    home: 'முகப்பு',
    ai_assistant: 'AI உதவியாளர்',
    market: 'சந்தை',
    community: 'சமூகம்',
    profile: 'சுயவிவரம்',
    welcome_to_kisanai: 'கிசான்ஏஐ-க்கு வரவேற்கிறோம்',
    welcome_message: 'வணக்கம், {{name}}!',
    smart_farming_partner: 'ஒரு சிறந்த அறுவடைக்கு உங்கள் έξυπனான விவசாய கூட்டாளி.',
    quick_actions: 'விரைவு நடவடிக்கைகள்',
    quick_links: 'விரைவு இணைப்புகள்',
    get_farming_advice: 'விவசாய ஆலோசனை பெறுங்கள்',
    market_prices: 'சந்தை விலைகள்',
    check_crop_prices: 'பயிர் விலைகளை சரிபார்க்கவும்',
    connect_with_farmers: 'விவசாயிகளுடன் இணையுங்கள்',
    customize_your_app: 'உங்கள் பயன்பாட்டைத் தனிப்பயனாக்குங்கள்',
    daily_tip: 'தினசரி உதவிக்குறிப்பு',
    daily_tip_content: 'உங்கள் வயல்களுக்கு நீர்ப்பாசனம் செய்வதற்கு முன் மண் ஈரப்பதத்தைச் சரிபார்க்கவும். அதிகப்படியான నీటిపారుదల తక్కువ నీటిపారుదల వలె హానికరం.',
    voice_assistant: 'குரல் உதவியாளர்',
    current_weather: 'தற்போதைய வானிலை',
    weather_forecast: 'வானிலை முன்னறிவிப்பு',
    today: 'இன்று',
    weather_error: 'வானிலை பிழை',
    humidity: 'ஈரப்பதம்',
    wind: 'காற்று',
    location_access_denied: 'இடத்திற்கான அணுகல் மறுக்கப்பட்டது',
    fallback_location_weather: 'வானிலைக்காக இயல்புநிலை இருப்பிடத்திற்குத் திரும்புகிறது.',
    latest_prices: 'பல்வேறு சந்தைகளிலிருந்து சமீபத்திய விவசாயப் பொருட்களின் விலைகள்.',
    showing_markets_near: 'அருகிலுள்ள சந்தைகளைக் காட்டுகிறது',
    crop: 'பயிர்',
    price_per_unit: 'விலை (ஒரு அலகுக்கு)',
    trend: 'போக்கு',
    last_updated: 'கடைசியாகப் புதுப்பிக்கப்பட்டது',
    community_feed: 'சமூக ஊட்டம்',
    create_a_post: 'ஒரு இடுகையை உருவாக்கவும்',
    whats_on_your_mind: 'உங்கள் மனதில் என்ன இருக்கிறது, விவசாயி?',
    login_or_signup: 'உள்நுழையவும் அல்லது பதிவு செய்யவும்',
    enter_mobile_for_otp: 'OTP பெற உங்கள் மொபைல் எண்ணை உள்ளிடவும்.',
    full_name: 'முழு பெயர்',
    enter_full_name: 'உங்கள் முழு பெயரை உள்ளிடவும்',
    mobile_number: 'மொபைல் எண்',
    enter_mobile_number: 'உங்கள் 10 இலக்க மொபைல் எண்ணை உள்ளிடவும்',
    send_otp: 'OTP அனுப்பவும்',
    my_profile: 'எனது சுயவிவரம்',
    view_manage_account: 'உங்கள் கணக்கு விவரங்களைக் கண்டு நிர்வகிக்கவும்.',
    name: 'பெயர்',
    log_out: 'வெளியேறு',
    choose_language: 'பயன்பாட்டிற்கு உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்.',
    notifications: 'அறிவிப்புகள்',
    enable_notifications: 'முக்கியமான எச்சரிக்கைகளுக்கு அறிவிப்புகளை இயக்கவும்.',
    enable_notifications_button: 'அறிவிப்புகளை இயக்கு',
    ai_farming_assistant: 'AI விவசாய உதவியாளர்',
    ask_me_anything: 'விவசாயம் பற்றி என்னிடம் எதுவும் கேளுங்கள்!',
    ask_about_crops: 'பயிர்கள், மண் அல்லது பூச்சிகள் பற்றி கேளுங்கள்...',
    assistant_can_mistake: 'கிசான்ஏஐ தவறுகள் செய்யலாம். முக்கியமான தகவல்களைச் சரிபார்க்கவும்.',
    voice_assistant_title: 'குரல் உதவியாளர்',
    listening: 'கேட்டுக்கொண்டிருக்கிறது...',
    processing: 'செயலாக்கப்படுகிறது...',
    ask_a_question: 'விவசாயம் பற்றி ஒரு கேள்வி கேளுங்கள்',
  },
  te: {
    welcome: 'స్వాగతం',
    settings: 'సెట్టింగ్‌లు',
    language: 'భాష',
    post: 'పోస్ట్ చేయండి',
    home: 'హోమ్',
    ai_assistant: 'AI సహాయకుడు',
    market: 'మార్కెట్',
    community: 'సంఘం',
    profile: 'ప్రొఫైల్',
    welcome_to_kisanai: 'కిసాన్‌ఏఐకి స్వాగతం',
    welcome_message: 'నమస్కారం, {{name}}!',
    smart_farming_partner: 'ఒక గొప్ప పంట కోసం మీ స్మార్ట్ వ్యవసాయ భాగస్వామి.',
    quick_actions: 'త్వరిత చర్యలు',
    quick_links: 'త్వరిత లింకులు',
    get_farming_advice: 'వ్యవసాయ సలహా పొందండి',
    market_prices: 'మార్కెట్ ధరలు',
    check_crop_prices: 'పంట ధరలను తనిఖీ చేయండి',
    connect_with_farmers: 'రైతులతో కనెక్ట్ అవ్వండి',
    customize_your_app: 'మీ అనువర్తనాన్ని అనుకూలీకరించండి',
    daily_tip: 'రోజువారీ చిట్కా',
    daily_tip_content: 'మీ పొలాలకు నీరు పెట్టే ముందు నేల తేమను తనిఖీ చేయండి. ఎక్కువ నీరు పెట్టడం కూడా తక్కువ నీరు పెట్టడం అంత హానికరం.',
    voice_assistant: 'వాయిస్ అసిస్టెంట్',
    current_weather: 'ప్రస్తుత వాతావరణం',
    weather_forecast: 'వాతావరణ సూచన',
    today: 'ఈ రోజు',
    weather_error: 'వాతావరణ లోపం',
    humidity: 'తేమ',
    wind: 'గాలి',
    location_access_denied: 'స్థాన ప్రాప్యత నిరాకరించబడింది',
    fallback_location_weather: 'వాతావరణం కోసం డిఫాల్ట్ స్థానానికి తిరిగి వెళుతోంది.',
    latest_prices: 'వివిధ మార్కెట్ల నుండి తాజా వ్యవసాయ వస్తువుల ధరలు.',
    showing_markets_near: 'దగ్గరలోని మార్కెట్లను చూపుతోంది',
    crop: 'పంట',
    price_per_unit: 'ధర (ఒక యూనిట్‌కు)',
    trend: 'ట్రెండ్',
    last_updated: 'చివరిగా నవీకరించబడింది',
    community_feed: 'సంఘం ఫీడ్',
    create_a_post: 'ఒక పోస్ట్‌ను సృష్టించండి',
    whats_on_your_mind: 'మీ మనస్సులో ఏముంది, రైతు?',
    login_or_signup: 'లాగిన్ లేదా సైన్ అప్ చేయండి',
    enter_mobile_for_otp: 'OTP స్వీకరించడానికి మీ మొబైల్ నంబర్‌ను నమోదు చేయండి.',
    full_name: 'పూర్తి పేరు',
    enter_full_name: 'మీ పూర్తి పేరును నమోదు చేయండి',
    mobile_number: 'మొబైల్ నంబర్',
    enter_mobile_number: 'మీ 10-అంకెల మొబైల్ నంబర్‌ను నమోదు చేయండి',
    send_otp: 'OTP పంపండి',
    my_profile: 'నా ప్రొఫైల్',
    view_manage_account: 'మీ ఖాతా వివరాలను వీక్షించండి మరియు నిర్వహించండి.',
    name: 'పేరు',
    log_out: 'లాగ్ అవుట్',
    choose_language: 'అనువర్తనం కోసం మీ ప్రాధాన్య భాషను ఎంచుకోండి.',
    notifications: 'నోటిఫికేషన్‌లు',
    enable_notifications: 'ముఖ్యమైన హెచ్చరికల కోసం నోటిఫికేషన్‌లను ప్రారంభించండి.',
    enable_notifications_button: 'నోటిఫికేషన్‌లను ప్రారంభించు',
    ai_farming_assistant: 'AI వ్యవసాయ సహాయకుడు',
    ask_me_anything: 'వ్యవసాయం గురించి నన్ను ఏదైనా అడగండి!',
    ask_about_crops: 'పంటలు, నేల లేదా తెగుళ్ళ గురించి అడగండి...',
    assistant_can_mistake: 'కిసాన్‌ఏఐ తప్పులు చేయవచ్చు. ముఖ్యమైన సమాచారాన్ని తనిఖీ చేయడాన్ని పరిగణించండి.',
    voice_assistant_title: 'వాయిస్ అసిస్టెంట్',
    listening: 'వింటున్నాను...',
    processing: 'ప్రాసెస్ చేస్తోంది...',
    ask_a_question: 'వ్యవసాయం గురించి ఒక ప్రశ్న అడగండి',
  },
  kn: {
    welcome: 'ಸ್ವಾಗತ',
    settings: 'ಸಂಯೋಜನೆಗಳು',
    language: 'ಭಾಷೆ',
    post: 'ಪೋಸ್ಟ್ ಮಾಡಿ',
    home: 'ಮನೆ',
    ai_assistant: 'AI ಸಹಾಯಕ',
    market: 'ಮಾರುಕಟ್ಟೆ',
    community: 'ಸಮುದಾಯ',
    profile: 'ಪ್ರೊಫೈಲ್',
    welcome_to_kisanai: 'ಕಿಸಾನ್‌ಎಐಗೆ ಸ್ವಾಗತ',
    welcome_message: 'ನಮಸ್ಕಾರ, {{name}}!',
    smart_farming_partner: 'ಉತ್ತಮ ಸುಗ್ಗಿಗಾಗಿ ನಿಮ್ಮ ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಪಾಲುದಾರ.',
    quick_actions: 'ತ್ವರಿತ ಕ್ರಮಗಳು',
    quick_links: 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು',
    get_farming_advice: 'ಕೃಷಿ ಸಲಹೆ ಪಡೆಯಿರಿ',
    market_prices: 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು',
    check_crop_prices: 'ಬೆಳೆ ಬೆಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
    connect_with_farmers: 'ರೈತರೊಂದಿಗೆ ಸಂಪರ್ಕ ಸಾಧಿಸಿ',
    customize_your_app: 'ನಿಮ್ಮ ಅಪ್ಲಿಕೇಶನ್ ಅನ್ನು ಕಸ್ಟಮೈಸ್ ಮಾಡಿ',
    daily_tip: 'ದೈನಂದಿನ ಸಲಹೆ',
    daily_tip_content: 'ನಿಮ್ಮ ಹೊಲಗಳಿಗೆ ನೀರುಣಿಸುವ ಮೊದಲು ಮಣ್ಣಿನ ತೇವಾಂಶವನ್ನು ಪರೀಕ್ಷಿಸಿ. ಹೆಚ್ಚು ನೀರುಣಿಸುವುದು ಕಡಿಮೆ ನೀರುಣಿಸುವಷ್ಟೇ ಹಾನಿಕಾರಕ.',
    voice_assistant: 'ಧ್ವನಿ ಸಹಾಯಕ',
    current_weather: 'ಪ್ರಸ್ತುತ ಹವಾಮಾನ',
    weather_forecast: 'ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ',
    today: 'ಇಂದು',
    weather_error: 'ಹವಾಮಾನ ದೋಷ',
    humidity: 'ತೇವಾಂಶ',
    wind: 'ಗಾಳಿ',
    location_access_denied: 'ಸ್ಥಳ ಪ್ರವೇಶವನ್ನು ನಿರಾಕರಿಸಲಾಗಿದೆ',
    fallback_location_weather: 'ಹವಾಮಾನಕ್ಕಾಗಿ ಡೀಫಾಲ್ಟ್ ಸ್ಥಳಕ್ಕೆ ಹಿಂತಿರುಗಲಾಗುತ್ತಿದೆ.',
    latest_prices: 'ವಿವಿಧ ಮಾರುಕಟ್ಟೆಗಳಿಂದ ಇತ್ತೀಚಿನ ಕೃಷಿ ಸರಕುಗಳ ಬೆಲೆಗಳು.',
    showing_markets_near: 'ಹತ್ತಿರದ ಮಾರುಕಟ್ಟೆಗಳನ್ನು ತೋರಿಸುತ್ತಿದೆ',
    crop: 'ಬೆಳೆ',
    price_per_unit: 'ಬೆಲೆ (ಪ್ರತಿ ಘಟಕಕ್ಕೆ)',
    trend: 'ಪ್ರವೃತ್ತಿ',
    last_updated: 'ಕೊನೆಯದಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ',
    community_feed: 'ಸಮುದಾಯ ಫೀಡ್',
    create_a_post: 'ಪೋಸ್ಟ್ ರಚಿಸಿ',
    whats_on_your_mind: 'ನಿಮ್ಮ ಮನಸ್ಸಿನಲ್ಲಿ ಏನಿದೆ, ರೈತ?',
    login_or_signup: 'ಲಾಗಿನ್ ಅಥವಾ ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    enter_mobile_for_otp: 'ಒಟಿಪಿ ಸ್ವೀಕರಿಸಲು ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.',
    full_name: 'ಪೂರ್ಣ ಹೆಸರು',
    enter_full_name: 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
    mobile_number: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    enter_mobile_number: 'ನಿಮ್ಮ 10-ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    send_otp: 'ಒಟಿಪಿ ಕಳುಹಿಸಿ',
    my_profile: 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    view_manage_account: 'ನಿಮ್ಮ ಖಾತೆ ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ ಮತ್ತು ನಿರ್ವಹಿಸಿ.',
    name: 'ಹೆಸರು',
    log_out: 'ಲಾಗ್ ಔಟ್',
    choose_language: 'ಅಪ್ಲಿಕೇಶನ್‌ಗಾಗಿ ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    enable_notifications: 'ಪ್ರಮುಖ ಎಚ್ಚರಿಕೆಗಳಿಗಾಗಿ ಅಧಿಸೂಚನೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ.',
    enable_notifications_button: 'ಅಧಿಸೂಚನೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ',
    ai_farming_assistant: 'AI ಕೃಷಿ ಸಹಾಯಕ',
    ask_me_anything: 'ಕೃಷಿ ಬಗ್ಗೆ ನನ್ನನ್ನು ಏನು ಬೇಕಾದರೂ ಕೇಳಿ!',
    ask_about_crops: 'ಬೆಳೆಗಳು, ಮಣ್ಣು, ಅಥವಾ ಕೀಟಗಳ ಬಗ್ಗೆ ಕೇಳಿ...',
    assistant_can_mistake: 'ಕಿಸಾನ್‌ಎಐ ತಪ್ಪುಗಳನ್ನು ಮಾಡಬಹುದು. ಪ್ರಮುಖ ಮಾಹಿತಿಯನ್ನು ಪರಿಶೀಲಿಸುವುದನ್ನು ಪರಿಗಣಿಸಿ.',
    voice_assistant_title: 'ಧ್ವನಿ ಸಹಾಯಕ',
    listening: 'ಕೇಳುತ್ತಿದೆ...',
    processing: 'ಸಂಸ್ಕರಿಸಲಾಗುತ್ತಿದೆ...',
    ask_a_question: 'ಕೃಷಿ ಬಗ್ಗೆ ಪ್ರಶ್ನೆ ಕೇಳಿ',
  },
  bn: {
    welcome: 'স্বাগত',
    settings: 'সেটিংস',
    language: 'ভাষা',
    post: 'পোস্ট করুন',
    home: 'হোম',
    ai_assistant: 'এআই সহকারী',
    market: 'বাজার',
    community: 'সম্প্রদায়',
    profile: 'প্রোফাইল',
    welcome_to_kisanai: 'কিসানএআই-তে স্বাগতম',
    welcome_message: 'নমস্কার, {{name}}!',
    smart_farming_partner: 'একটি সমৃদ্ধ ফসলের জন্য আপনার স্মার্ট চাষ অংশীদার।',
    quick_actions: 'দ্রুত ক্রিয়া',
    quick_links: 'দ্রুত লিঙ্ক',
    get_farming_advice: 'চাষের পরামর্শ নিন',
    market_prices: 'বাজার দর',
    check_crop_prices: 'ফসলের দাম পরীক্ষা করুন',
    connect_with_farmers: 'চাষীদের সাথে সংযোগ স্থাপন করুন',
    customize_your_app: 'আপনার অ্যাপটি কাস্টমাইজ করুন',
    daily_tip: 'দৈনিক টিপ',
    daily_tip_content: 'আপনার জমিতে সেচ দেওয়ার আগে মাটির আর্দ্রতা পরীক্ষা করুন। অতিরিক্ত জল দেওয়া কম জল দেওয়ার মতোই ক্ষতিকর হতে পারে।',
    voice_assistant: 'ভয়েস সহকারী',
    current_weather: 'বর্তমান আবহাওয়া',
    weather_forecast: 'আবহাওয়ার পূর্বাভাস',
    today: 'আজ',
    weather_error: 'আবহাওয়ার ত্রুটি',
    humidity: 'আর্দ্রতা',
    wind: 'বাতাস',
    location_access_denied: 'অবস্থান অ্যাক্সেস অস্বীকার করা হয়েছে',
    fallback_location_weather: 'আবহাওয়ার জন্য ডিফল্ট অবস্থানে ফিরে যাওয়া হচ্ছে।',
    latest_prices: 'বিভিন্ন বাজার থেকে সর্বশেষ কৃষি পণ্যের দাম।',
    showing_markets_near: 'কাছাকাছি বাজার দেখাচ্ছে',
    crop: 'ফসল',
    price_per_unit: 'দাম (প্রতি ইউনিটে)',
    trend: 'প্রবণতা',
    last_updated: 'শেষ আপডেট',
    community_feed: 'সম্প্রদায় ফিড',
    create_a_post: 'একটি পোস্ট তৈরি করুন',
    whats_on_your_mind: 'আপনার মনে কি আছে, কৃষক?',
    login_or_signup: 'লগইন বা সাইন আপ করুন',
    enter_mobile_for_otp: 'ওটিপি পেতে আপনার মোবাইল নম্বর লিখুন।',
    full_name: 'পুরো নাম',
    enter_full_name: 'আপনার পুরো নাম লিখুন',
    mobile_number: 'মোবাইল নম্বর',
    enter_mobile_number: 'আপনার ১০-সংখ্যার মোবাইল নম্বর লিখুন',
    send_otp: 'ওটিপি পাঠান',
    my_profile: 'আমার প্রোফাইল',
    view_manage_account: 'আপনার অ্যাকাউন্টের বিবরণ দেখুন এবং পরিচালনা করুন।',
    name: 'নাম',
    log_out: 'লগ আউট',
    choose_language: 'অ্যাপের জন্য আপনার পছন্দের ভাষা চয়ন করুন।',
    notifications: 'বিজ্ঞপ্তি',
    enable_notifications: 'গুরুত্বপূর্ণ সতর্কতার জন্য বিজ্ঞপ্তি সক্ষম করুন।',
    enable_notifications_button: 'বিজ্ঞপ্তি সক্ষম করুন',
    ai_farming_assistant: 'এআই চাষ সহকারী',
    ask_me_anything: 'চাষাবাদ সম্পর্কে আমাকে কিছু জিজ্ঞাসা করুন!',
    ask_about_crops: 'ফসল, মাটি বা কীটপতঙ্গ সম্পর্কে জিজ্ঞাসা করুন...',
    assistant_can_mistake: 'কিসানএআই ভুল করতে পারে। গুরুত্বপূর্ণ তথ্য পরীক্ষা করার কথা বিবেচনা করুন।',
    voice_assistant_title: 'ভয়েস সহকারী',
    listening: 'শুনছি...',
    processing: 'প্রসেস করা হচ্ছে...',
    ask_a_question: 'চাষাবাদ সম্পর্কে একটি প্রশ্ন জিজ্ঞাসা করুন',
  },
  pa: {
    welcome: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    settings: 'ਸੈਟਿੰਗਾਂ',
    language: 'ਭਾਸ਼ਾ',
    post: 'ਪੋਸਟ ਕਰੋ',
    home: 'ਮੁੱਖ',
    ai_assistant: 'ਏਆਈ ਸਹਾਇਕ',
    market: 'ਬਾਜ਼ਾਰ',
    community: 'ਭਾਈਚਾਰਾ',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    welcome_to_kisanai: 'ਕਿਸਾਨਏਆਈ ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ',
    welcome_message: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ, {{name}}!',
    smart_farming_partner: 'ਇੱਕ ਅਮੀਰ ਫਸਲ ਲਈ ਤੁਹਾਡਾ ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ ਸਾਥੀ।',
    quick_actions: 'ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ',
    quick_links: 'ਤੁਰੰਤ ਲਿੰਕ',
    get_farming_advice: 'ਖੇਤੀਬਾੜੀ ਸਲਾਹ ਲਵੋ',
    market_prices: 'ਬਾਜ਼ਾਰ ਦੀਆਂ ਕੀਮਤਾਂ',
    check_crop_prices: 'ਫਸਲਾਂ ਦੀਆਂ ਕੀਮਤਾਂ ਦੀ ਜਾਂਚ ਕਰੋ',
    connect_with_farmers: 'ਕਿਸਾਨਾਂ ਨਾਲ ਜੁੜੋ',
    customize_your_app: 'ਆਪਣੀ ਐਪ ਨੂੰ ਅਨੁਕੂਲਿਤ ਕਰੋ',
    daily_tip: 'ਰੋਜ਼ਾਨਾ ਸੁਝਾਅ',
    daily_tip_content: 'ਆਪਣੇ ਖੇਤਾਂ ਨੂੰ ਸਿੰਜਾਈ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਮਿੱਟੀ ਦੀ ਨਮੀ ਦੀ ਜਾਂਚ ਕਰੋ। ਵੱਧ ਪਾਣੀ ਦੇਣਾ ਘੱਟ ਪਾਣੀ ਦੇਣ ਵਾਂਗ ਹੀ ਨੁਕਸਾਨਦੇਹ ਹੋ ਸਕਦਾ ਹੈ।',
    voice_assistant: 'ਆਵਾਜ਼ ਸਹਾਇਕ',
    current_weather: 'ਮੌਜੂਦਾ ਮੌਸਮ',
    weather_forecast: 'ਮੌਸਮ ਦੀ ਭਵਿੱਖਬਾਣੀ',
    today: 'ਅੱਜ',
    weather_error: 'ਮੌਸਮ ਵਿੱਚ ਗਲਤੀ',
    humidity: 'ਨਮੀ',
    wind: 'ਹਵਾ',
    location_access_denied: 'ਸਥਾਨ ਪਹੁੰਚ ਤੋਂ ਇਨਕਾਰ ਕੀਤਾ ਗਿਆ',
    fallback_location_weather: 'ਮੌਸਮ ਲਈ ਡਿਫੌਲਟ ਸਥਾਨ ਤੇ ਵਾਪਸ ਜਾ ਰਿਹਾ ਹੈ।',
    latest_prices: 'ਵੱਖ-ਵੱਖ ਬਾਜ਼ਾਰਾਂ ਤੋਂ ਨਵੀਨਤਮ ਖੇਤੀਬਾੜੀ ਵਸਤਾਂ ਦੀਆਂ ਕੀਮਤਾਂ।',
    showing_markets_near: 'ਨੇੜਲੇ ਬਾਜ਼ਾਰਾਂ ਨੂੰ ਦਿਖਾ ਰਿਹਾ ਹੈ',
    crop: 'ਫਸਲ',
    price_per_unit: 'ਕੀਮਤ (ਪ੍ਰਤੀ ਯੂਨਿਟ)',
    trend: 'ਰੁਝਾਨ',
    last_updated: 'ਆਖਰੀ ਵਾਰ ਅੱਪਡੇਟ ਕੀਤਾ ਗਿਆ',
    community_feed: 'ਭਾਈਚਾਰਕ ਫੀਡ',
    create_a_post: 'ਇੱਕ ਪੋਸਟ ਬਣਾਓ',
    whats_on_your_mind: 'ਤੁਹਾਡੇ ਮਨ ਵਿੱਚ ਕੀ ਹੈ, ਕਿਸਾਨ?',
    login_or_signup: 'ਲੌਗਇਨ ਜਾਂ ਸਾਈਨ ਅੱਪ ਕਰੋ',
    enter_mobile_for_otp: 'ਓਟੀਪੀ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਆਪਣਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ।',
    full_name: 'ਪੂਰਾ ਨਾਮ',
    enter_full_name: 'ਆਪਣਾ ਪੂਰਾ ਨਾਮ ਦਰਜ ਕਰੋ',
    mobile_number: 'ਮੋਬਾਈਲ ਨੰਬਰ',
    enter_mobile_number: 'ਆਪਣਾ 10-ਅੰਕਾਂ ਵਾਲਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ',
    send_otp: 'ਓਟੀਪੀ ਭੇਜੋ',
    my_profile: 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
    view_manage_account: 'ਆਪਣੇ ਖਾਤੇ ਦੇ ਵੇਰਵੇ ਵੇਖੋ ਅਤੇ ਪ੍ਰਬੰਧਿਤ ਕਰੋ।',
    name: 'ਨਾਮ',
    log_out: 'ਲੌਗ ਆਉਟ',
    choose_language: 'ਐਪ ਲਈ ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ।',
    notifications: 'ਸੂਚਨਾਵਾਂ',
    enable_notifications: 'ਮਹੱਤਵਪੂਰਨ ਚੇਤਾਵਨੀਆਂ ਲਈ ਸੂਚਨਾਵਾਂ ਨੂੰ ਸਮਰੱਥ ਬਣਾਓ।',
    enable_notifications_button: 'ਸੂਚਨਾਵਾਂ ਨੂੰ ਸਮਰੱਥ ਬਣਾਓ',
    ai_farming_assistant: 'ਏਆਈ ਖੇਤੀਬਾੜੀ ਸਹਾਇਕ',
    ask_me_anything: 'ਖੇਤੀਬਾੜੀ ਬਾਰੇ ਮੈਨੂੰ ਕੁਝ ਵੀ ਪੁੱਛੋ!',
    ask_about_crops: 'ਫਸਲਾਂ, ਮਿੱਟੀ, ਜਾਂ ਕੀੜਿਆਂ ਬਾਰੇ ਪੁੱਛੋ...',
    assistant_can_mistake: 'ਕਿਸਾਨਏਆਈ ਗਲਤੀਆਂ ਕਰ ਸਕਦਾ ਹੈ। ਮਹੱਤਵਪੂਰਨ ਜਾਣਕਾਰੀ ਦੀ ਜਾਂਚ ਕਰਨ ਬਾਰੇ ਸੋਚੋ।',
    voice_assistant_title: 'ਆਵਾਜ਼ ਸਹਾਇਕ',
    listening: 'ਸੁਣ ਰਿਹਾ ਹਾਂ...',
    processing: 'ਪ੍ਰੋਸੈਸਿੰਗ ਹੋ ਰਹੀ ਹੈ...',
    ask_a_question: 'ਖੇਤੀਬਾੜੀ ਬਾਰੇ ਇੱਕ ਸਵਾਲ ਪੁੱਛੋ',
  },
  gu: {
    welcome: 'પધારો',
    settings: 'સેટિંગ્સ',
    language: 'ભાષા',
    post: 'પોસ્ટ કરો',
    home: 'હોમ',
    ai_assistant: 'AI સહાયક',
    market: 'બજાર',
    community: 'સમુદાય',
    profile: 'પ્રોફાઇલ',
    welcome_to_kisanai: 'કિસાનએઆઈમાં આપનું સ્વાગત છે',
    welcome_message: 'નમસ્તે, {{name}}!',
    smart_farming_partner: 'એક સમૃદ્ધ પાક માટે તમારા સ્માર્ટ ખેતી ભાગીદાર.',
    quick_actions: 'ઝડપી ક્રિયાઓ',
    quick_links: 'ઝડપી લિંક્સ',
    get_farming_advice: 'ખેતીની સલાહ મેળવો',
    market_prices: 'બજાર ભાવ',
    check_crop_prices: 'પાકના ભાવ તપાસો',
    connect_with_farmers: 'ખેડૂતો સાથે જોડાઓ',
    customize_your_app: 'તમારી એપ્લિકેશનને કસ્ટમાઇઝ કરો',
    daily_tip: 'દૈનિક ટીપ',
    daily_tip_content: 'તમારા ખેતરોમાં સિંચાઈ કરતા પહેલા જમીનની ભેજ તપાસો. વધુ પડતું પાણી આપવું એ ઓછું પાણી આપવા જેટલું જ હાનિકારક હોઈ શકે છે.',
    voice_assistant: 'વૉઇસ સહાયક',
    current_weather: 'વર્તમાન હવામાન',
    weather_forecast: 'હવામાનની આગાહી',
    today: 'આજે',
    weather_error: 'હવામાન ભૂલ',
    humidity: 'ભેજ',
    wind: 'પવન',
    location_access_denied: 'સ્થાન ઍક્સેસ નકારી',
    fallback_location_weather: 'હવામાન માટે ડિફૉલ્ટ સ્થાન પર પાછા ફરી રહ્યા છીએ.',
    latest_prices: 'વિવિધ બજારોમાંથી નવીનતમ કૃષિ કોમોડિટીના ભાવ.',
    showing_markets_near: 'નજીકના બજારો બતાવી રહ્યું છે',
    crop: 'પાક',
    price_per_unit: 'કિંમત (એકમ દીઠ)',
    trend: 'વલણ',
    last_updated: 'છેલ્લે અપડેટ કર્યું',
    community_feed: 'સમુદાય ફીડ',
    create_a_post: 'એક પોસ્ટ બનાવો',
    whats_on_your_mind: 'તમારા મનમાં શું છે, ખેડૂત?',
    login_or_signup: 'લૉગિન અથવા સાઇન અપ કરો',
    enter_mobile_for_otp: 'OTP મેળવવા માટે તમારો મોબાઇલ નંબર દાખલ કરો.',
    full_name: 'પૂરું નામ',
    enter_full_name: 'તમારું પૂરું નામ દાખલ કરો',
    mobile_number: 'મોબાઇલ નંબર',
    enter_mobile_number: 'તમારો 10-અંકનો મોબાઇલ નંબર દાખલ કરો',
    send_otp: 'OTP મોકલો',
    my_profile: 'મારી પ્રોફાઇલ',
    view_manage_account: 'તમારા એકાઉન્ટની વિગતો જુઓ અને મેનેજ કરો.',
    name: 'નામ',
    log_out: 'લૉગ આઉટ',
    choose_language: 'એપ્લિકેશન માટે તમારી પસંદગીની ભાષા પસંદ કરો.',
    notifications: 'સૂચનાઓ',
    enable_notifications: 'મહત્વપૂર્ણ ચેતવણીઓ માટે સૂચનાઓ સક્ષમ કરો.',
    enable_notifications_button: 'સૂચનાઓ સક્ષમ કરો',
    ai_farming_assistant: 'AI ખેતી સહાયક',
    ask_me_anything: 'ખેતી વિશે મને કંઈપણ પૂછો!',
    ask_about_crops: 'પાક, જમીન અથવા જીવાતો વિશે પૂછો...',
    assistant_can_mistake: 'કિસાનએઆઈ ભૂલો કરી શકે છે. મહત્વપૂર્ણ માહિતી તપાસવાનું વિચારો.',
    voice_assistant_title: 'વૉઇસ સહાયક',
    listening: 'સાંભળી રહ્યું છે...',
    processing: 'પ્રક્રિયા કરી રહ્યું છે...',
    ask_a_question: 'ખેતી વિશે એક પ્રશ્ન પૂછો',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');
  
  const t = (key: string, values: {[key: string]: string | number} = {}): string => {
    const translationSet = translations[language] || translations.en;
    let translation = translationSet[key as keyof typeof translationSet] || key;
    
    Object.keys(values).forEach(k => {
        translation = translation.replace(`{{${k}}}`, String(values[k]));
    });

    return translation;
  };
  
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
