
'use client';

import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'mr' | 'ta' | 'te' | 'kn' | 'bn' | 'pa' | 'gu';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  // A t function that can handle placeholders
  t: (key: string, values?: {[key: string]: string | number}) => string;
}

const translations = {
  en: {
    // General
    welcome: 'Welcome',
    settings: 'Settings',
    language: 'Language',
    post: 'Post',
    // Header
    home: 'Home',
    ai_assistant: 'AI Assistant',
    plant_doctor: 'Plant Doctor',
    market: 'Market',
    community: 'Community',
    profile: 'Profile',
    // Home Page
    welcome_to_kisanai: 'Welcome to KisanAI',
    welcome_message: 'Welcome, {{name}}!',
    smart_farming_partner: 'Your smart farming partner for a richer harvest.',
    quick_actions: 'Quick Actions',
    quick_links: 'Quick Links',
    get_farming_advice: 'Get farming advice',
    market_prices: 'Market Prices',
    check_crop_prices: 'Check crop prices',
    connect_with_farmers: 'Connect with farmers',
    customize_your_app: 'Customize your app',
    daily_tip: 'Daily Tip',
    daily_tip_content: 'Check soil moisture before irrigating your fields. Over-watering can be as harmful as under-watering.',
    voice_assistant: 'Voice Assistant',
    // Weather Card
    current_weather: 'Current Weather',
    weather_forecast: 'Weather Forecast',
    today: 'Today',
    weather_error: 'Weather Error',
    humidity: 'Humidity',
    wind: 'Wind',
    location_access_denied: 'Location Access Denied',
    fallback_location_weather: 'Falling back to default location for weather.',
    // Market Page
    latest_prices: 'Latest agricultural commodity prices from various markets.',
    showing_markets_near: 'Showing markets near',
    crop: 'Crop',
    price_per_unit: 'Price (per unit)',
    trend: 'Trend',
    last_updated: 'Last Updated',
    // Community Page
    community_feed: 'Community Feed',
    create_a_post: 'Create a Post',
    whats_on_your_mind: "What's on your mind, farmer?",
    post_not_found: 'Post not found',
    back_to_community: 'Back to community',
    likes: 'Likes',
    comments: 'Comments',
    leave_a_comment: 'Leave a comment',
    write_your_comment: 'Write your comment...',
    comment: 'Comment',
    reply: 'Reply',
    reply_to: 'Reply to',
    no_comments_yet: 'No comments yet. Be the first to comment!',
    login_to_post: 'Login required',
    login_to_post_description: 'You need to be logged in to create a post.',
    cannot_post_empty: 'Post content cannot be empty.',
    post_created: 'Post created successfully!',
    error_creating_post: 'Error creating post.',
    login_to_comment: 'Login required',
    login_to_comment_desc: 'You need to be logged in to comment.',
    cannot_post_empty_comment: 'Comment cannot be empty.',
    comment_posted: 'Comment posted!',
    error_posting_comment: 'Error posting comment.',
    // Profile Page
    login_or_signup: 'Login or Sign Up',
    enter_mobile_for_otp: 'Enter your mobile number to receive an OTP.',
    full_name: 'Full Name',
    enter_full_name: 'Enter your full name',
    mobile_number: 'Mobile Number',
    enter_mobile_number: 'Enter your 10-digit mobile number',
    send_otp: 'Send OTP',
    my_profile: 'My Profile',
    view_manage_account: 'View and manage your account details.',
    name: 'Name',
    state: 'State',
    select_state: 'Select your state',
    district: 'District',
    select_district: 'Select your district',
    village_town: 'Village / Town',
    enter_village_town: 'Enter your village or town name',
    save_changes: 'Save Changes',
    log_out: 'Log Out',
    profile_updated_title: 'Profile Updated',
    profile_updated_description: 'Your profile has been saved successfully.',
    could_not_save_profile: 'Could not save profile.',
    login_failed: 'Login Failed',
    login_failed_description: 'Could not sign you in. Please try again.',
    // Settings Page
    choose_language: 'Choose your preferred language for the app.',
    notifications: 'Notifications',
    enable_notifications: 'Enable notifications for important alerts.',
    enable_notifications_button: 'Enable Notifications',
    // Assistant Page
    ai_farming_assistant: 'AI Farming Assistant',
    ask_me_anything: 'Ask me anything about farming!',
    ask_about_crops: 'Ask about crops, soil, or pests...',
    assistant_can_mistake: 'KisanAI can make mistakes. Consider checking important information.',
    // Voice Assistant
    voice_assistant_title: 'Voice Assistant',
    listening: 'Listening...',
    processing: 'Processing...',
    ask_a_question: 'Ask a question about farming',
    // Plant Doctor
    plant_doctor_description: 'Capture or upload a photo of your plant and add a voice note for an AI diagnosis.',
    step_1_image: '1. Provide an Image',
    use_camera_or_upload: 'Use your camera or upload an image to begin.',
    camera_access_denied_title: 'Camera Access Denied',
    camera_access_denied_description: 'Please enable camera permissions in your browser settings to use this feature.',
    capture_photo: 'Capture Photo',
    use_camera: 'Use Camera',
    upload_image: 'Upload Image',
    step_2_voice_note: '2. Add a Voice Note (Optional)',
    voice_note_placeholder: 'Your transcribed voice note will appear here...',
    get_diagnosis: 'Get Diagnosis',
    diagnosing: 'Diagnosing...',
    new_diagnosis: 'Start New Diagnosis',
    plant_diagnosis_report: 'Plant Diagnosis Report',
    confidence: 'Confidence',
    quick_summary: 'Quick Summary',
    identification: 'Identification',
    primary_species: 'Primary Species',
    could_not_identify: 'Could not identify plant species.',
    diagnosis: 'Diagnosis',
    severity: 'Severity',
    likelihood: 'Likelihood',
    evidence: 'Evidence',
    no_issues_diagnosed: 'No specific issues diagnosed.',
    recommendations: 'Recommendations',
    cultural_ipm: 'Cultural & IPM',
    organic_biological: 'Organic/Biological',
    image_quality: 'Image Quality',
    quality: 'Quality',
    suggestions: 'Suggestions',
    disease: 'disease',
    pest: 'pest',
    nutrient: 'nutrient',
    physiological: 'physiological',
    camera_not_supported_title: 'Camera Not Supported',
    camera_not_supported_description: 'Your browser does not support camera access.',
    browser_not_supported_title: 'Browser Not Supported',
    browser_not_supported_description: 'Your browser does not support voice recognition.',
    no_image_title: 'No Image',
    no_image_description: 'Please provide an image first.',
    diagnosis_failed_title: 'Diagnosis Failed',
    diagnosis_failed_description: 'An error occurred while analyzing the plant. Please try again.',
  },
  hi: {
    // General
    welcome: 'स्वागत है',
    settings: 'सेटिंग्स',
    language: 'भाषा',
    post: 'पोस्ट करें',
    // Header
    home: 'होम',
    ai_assistant: 'एआई सहायक',
    plant_doctor: 'प्लांट डॉक्टर',
    market: 'बाजार',
    community: 'समुदाय',
    profile: 'प्रोफ़ाइल',
    // Home Page
    welcome_to_kisanai: 'किसान-एआई में आपका स्वागत है',
    welcome_message: 'नमस्ते, {{name}}!',
    smart_farming_partner: 'एक समृद्ध फसल के लिए आपका स्मार्ट खेती पार्टनर।',
    quick_actions: 'त्वरित कार्रवाइयां',
    quick_links: 'त्वरित लिंक',
    get_farming_advice: 'खेती की सलाह लें',
    market_prices: 'बाजार मूल्य',
    check_crop_prices: 'फसलों की कीमतें जांचें',
    connect_with_farmers: 'किसानों से जुड़ें',
    customize_your_app: 'अपने ऐप को कस्टमाइज़ करें',
    daily_tip: 'आज का सुझाव',
    daily_tip_content: 'अपने खेतों की सिंचाई करने से पहले मिट्टी की नमी की जाँच करें। ज़्यादा पानी देना भी कम पानी देने जितना ही हानिकारक हो सकता है।',
    voice_assistant: 'आवाज सहायक',
    // Weather Card
    current_weather: 'वर्तमान मौसम',
    weather_forecast: 'मौसम पूर्वानुमान',
    today: 'आज',
    weather_error: 'मौसम त्रुटि',
    humidity: 'नमी',
    wind: 'हवा',
    location_access_denied: 'स्थान पहुंच अस्वीकृत',
    fallback_location_weather: 'मौसम के लिए डिफ़ॉल्ट स्थान पर वापस जा रहे हैं।',
    // Market Page
    latest_prices: 'विभिन्न बाजारों से नवीनतम कृषि जिंसों की कीमतें।',
    showing_markets_near: 'के पास के बाजार दिखा रहा है',
    crop: 'फसल',
    price_per_unit: 'मूल्य (प्रति यूनिट)',
    trend: 'प्रवृत्ति',
    last_updated: 'पिछला अपडेट',
    // Community Page
    community_feed: 'सामुदायिक फ़ीड',
    create_a_post: 'एक पोस्ट बनाएं',
    whats_on_your_mind: 'आपके मन में क्या है, किसान?',
    post_not_found: 'पोस्ट नहीं मिला',
    back_to_community: 'समुदाय पर वापस जाएं',
    likes: 'लाइक',
    comments: 'टिप्पणियाँ',
    leave_a_comment: 'एक टिप्पणी छोड़ें',
    write_your_comment: 'अपनी टिप्पणी लिखें...',
    comment: 'टिप्पणी',
    reply: 'उत्तर',
    reply_to: 'को उत्तर दें',
    no_comments_yet: 'अभी तक कोई टिप्पणी नहीं है। टिप्पणी करने वाले पहले व्यक्ति बनें!',
    login_to_post: 'लॉगिन आवश्यक है',
    login_to_post_description: 'पोस्ट बनाने के लिए आपको लॉग इन होना चाहिए।',
    cannot_post_empty: 'पोस्ट की सामग्री खाली नहीं हो सकती।',
    post_created: 'पोस्ट सफलतापूर्वक बनाया गया!',
    error_creating_post: 'पोस्ट बनाने में त्रुटि।',
    login_to_comment: 'लॉगिन आवश्यक है',
    login_to_comment_desc: 'टिप्पणी करने के लिए आपको लॉग इन होना चाहिए।',
    cannot_post_empty_comment: 'टिप्पणी खाली नहीं हो सकती।',
    comment_posted: 'टिप्पणी पोस्ट की गई!',
    error_posting_comment: 'टिप्पणी पोस्ट करने में त्रुटि।',
    // Profile Page
    login_or_signup: 'लॉग इन करें या साइन अप करें',
    enter_mobile_for_otp: 'ओटीपी प्राप्त करने के लिए अपना मोबाइल नंबर दर्ज करें।',
    full_name: 'पूरा नाम',
    enter_full_name: 'अपना पूरा नाम दर्ज करें',
    mobile_number: 'मोबाइल नंबर',
    enter_mobile_number: 'अपना 10 अंकों का मोबाइल नंबर दर्ज करें',
    send_otp: 'ओटीपी भेजें',
    my_profile: 'मेरी प्रोफ़ाइल',
    view_manage_account: 'अपने खाते का विवरण देखें और प्रबंधित करें।',
    name: 'नाम',
    state: 'राज्य',
    select_state: 'अपना राज्य चुनें',
    district: 'जिला',
    select_district: 'अपना जिला चुनें',
    village_town: 'गाँव / कस्बा',
    enter_village_town: 'अपने गाँव या कस्बे का नाम दर्ज करें',
    save_changes: 'बदलाव सहेजें',
    log_out: 'लॉग आउट',
    profile_updated_title: 'प्रोफ़ाइल अपडेट किया गया',
    profile_updated_description: 'आपकी प्रोफ़ाइल सफलतापूर्वक सहेज ली गई है।',
    could_not_save_profile: 'प्रोफ़ाइल सहेजा नहीं जा सका।',
    login_failed: 'लॉगिन विफल',
    login_failed_description: 'आपको साइन इन नहीं किया जा सका। कृपया पुनः प्रयास करें।',
    // Settings Page
    choose_language: 'ऐप के लिए अपनी पसंदीदा भाषा चुनें।',
    notifications: 'सूचनाएं',
    enable_notifications: 'महत्वपूर्ण सूचनाओं के लिए सूचनाएं सक्षम करें।',
    enable_notifications_button: 'सूचनाएं सक्षम करें',
    // Assistant Page
    ai_farming_assistant: 'एआई खेती सहायक',
    ask_me_anything: 'मुझसे खेती के बारे में कुछ भी पूछें!',
    ask_about_crops: 'फसलों, मिट्टी, या कीटों के बारे में पूछें...',
    assistant_can_mistake: 'किसान-एआई गलतियाँ कर सकता है। महत्वपूर्ण जानकारी की जाँच करने पर विचार करें।',
    // Voice Assistant
    voice_assistant_title: 'आवाज सहायक',
    listening: 'सुन रहा हूँ...',
    processing: 'संसाधित हो रहा है...',
    ask_a_question: 'खेती के बारे में एक प्रश्न पूछें',
    // Plant Doctor
    plant_doctor_description: 'एक एआई निदान के लिए अपने पौधे की तस्वीर खींचे या अपलोड करें और एक वॉयस नोट जोड़ें।',
    step_1_image: '1. एक छवि प्रदान करें',
    use_camera_or_upload: 'शुरू करने के लिए अपने कैमरे का उपयोग करें या एक छवि अपलोड करें।',
    camera_access_denied_title: 'कैमरा एक्सेस अस्वीकृत',
    camera_access_denied_description: 'इस सुविधा का उपयोग करने के लिए कृपया अपनी ब्राउज़र सेटिंग्स में कैमरा अनुमतियों को सक्षम करें।',
    capture_photo: 'फोटो खींचे',
    use_camera: 'कैमरे का उपयोग करें',
    upload_image: 'छवि अपलोड करें',
    step_2_voice_note: '2. एक वॉयस नोट जोड़ें (वैकल्पिक)',
    voice_note_placeholder: 'आपका ट्रांसक्राइब्ड वॉयस नोट यहां दिखाई देगा...',
    get_diagnosis: 'निदान प्राप्त करें',
    diagnosing: 'निदान हो रहा है...',
    new_diagnosis: 'नया निदान शुरू करें',
    plant_diagnosis_report: 'पौधा निदान रिपोर्ट',
    confidence: 'आत्मविश्वास',
    quick_summary: 'त्वरित सारांश',
    identification: 'पहचान',
    primary_species: 'प्राथमिक प्रजाति',
    could_not_identify: 'पौधे की प्रजातियों की पहचान नहीं हो सकी।',
    diagnosis: 'निदान',
    severity: 'गंभीरता',
    likelihood: 'संभावना',
    evidence: 'सबूत',
    no_issues_diagnosed: 'कोई विशेष समस्या का निदान नहीं हुआ।',
    recommendations: 'सिफारिशें',
    cultural_ipm: 'सांस्कृतिक और आईपीएम',
    organic_biological: 'जैविक/जैविक',
    image_quality: 'छवि गुणवत्ता',
    quality: 'गुणवत्ता',
    suggestions: 'सुझाव',
    disease: 'रोग',
    pest: 'कीट',
    nutrient: 'पोषक तत्व',
    physiological: 'शारीरिक',
    camera_not_supported_title: 'कैमरा समर्थित नहीं है',
    camera_not_supported_description: 'आपका ब्राउज़र कैमरा एक्सेस का समर्थन नहीं करता है।',
    browser_not_supported_title: 'ब्राउज़र समर्थित नहीं है',
    browser_not_supported_description: 'आपका ब्राउज़र आवाज पहचान का समर्थन नहीं करता है।',
    no_image_title: 'कोई छवि नहीं',
    no_image_description: 'कृपया पहले एक छवि प्रदान करें।',
    diagnosis_failed_title: 'निदान विफल',
    diagnosis_failed_description: 'पौधे का विश्लेषण करते समय एक त्रुटि हुई। कृपया पुनः प्रयास करें।',
  },
  mr: {
    // General
    welcome: 'स्वागत आहे',
    settings: 'सेटिंग्ज',
    language: 'भाषा',
    post: 'पोस्ट करा',
    // Header
    home: 'होम',
    ai_assistant: 'एआय सहाय्यक',
    plant_doctor: 'प्लांट डॉक्टर',
    market: 'बाजार',
    community: 'समुदाय',
    profile: 'प्रोफाइल',
    // Home Page
    welcome_to_kisanai: 'किसान-एआय मध्ये आपले स्वागत आहे',
    welcome_message: 'नमस्कार, {{name}}!',
    smart_farming_partner: 'अधिक समृद्ध पिकासाठी तुमचा स्मार्ट शेती भागीदार.',
    quick_actions: 'द्रुत क्रिया',
    quick_links: 'द्रुत दुवे',
    get_farming_advice: 'शेतीविषयक सल्ला मिळवा',
    market_prices: 'बाजारभाव',
    check_crop_prices: 'पिकांच्या किमती तपासा',
    connect_with_farmers: 'शेतकऱ्यांशी संपर्क साधा',
    customize_your_app: 'तुमचे ॲप सानुकूलित करा',
    daily_tip: 'आजचा सल्ला',
    daily_tip_content: 'आपल्या शेतात सिंचन करण्यापूर्वी जमिनीतील ओलावा तपासा. जास्त पाणी देणे हे कमी पाणी देण्याइतकेच हानिकारक असू शकते.',
    voice_assistant: 'आवाज सहाय्यक',
    // Weather Card
    current_weather: 'सध्याचे हवामान',
    weather_forecast: 'हवामान अंदाज',
    today: 'आज',
    weather_error: 'हवामान त्रुटी',
    humidity: 'आर्द्रता',
    wind: 'वारा',
    location_access_denied: 'स्थान प्रवेश नाकारला',
    fallback_location_weather: 'हवामानासाठी डीफॉल्ट स्थानावर परत जात आहे.',
    // Market Page
    latest_prices: 'विविध बाजारांतील नवीनतम कृषी मालाच्या किमती.',
    showing_markets_near: 'जवळपासची बाजारपेठ दाखवत आहे',
    crop: 'पीक',
    price_per_unit: 'किंमत (प्रति युनिट)',
    trend: 'कल',
    last_updated: 'शेवटचे अद्यतन',
    // Community Page
    community_feed: 'कम्युनिटी फीड',
    create_a_post: 'पोस्ट तयार करा',
    whats_on_your_mind: 'तुमच्या मनात काय आहे, शेतकरी?',
    post_not_found: 'पोस्ट सापडली नाही',
    back_to_community: 'समुदायावर परत जा',
    likes: 'लाइक',
    comments: 'टिप्पण्या',
    leave_a_comment: 'एक टिप्पणी द्या',
    write_your_comment: 'आपली टिप्पणी लिहा...',
    comment: 'टिप्पणी',
    reply: 'उत्तर',
    reply_to: 'ला उत्तर द्या',
    no_comments_yet: 'अद्याप कोणत्याही टिप्पण्या नाहीत. टिप्पणी करणारे पहिले व्हा!',
    login_to_post: 'लॉगिन आवश्यक आहे',
    login_to_post_description: 'पोस्ट तयार करण्यासाठी आपल्याला लॉगिन करणे आवश्यक आहे.',
    cannot_post_empty: 'पोस्टची सामग्री रिक्त असू शकत नाही.',
    post_created: 'पोस्ट यशस्वीरित्या तयार केले!',
    error_creating_post: 'पोस्ट तयार करताना त्रुटी.',
    login_to_comment: 'लॉगिन आवश्यक आहे',
    login_to_comment_desc: 'टिप्पणी करण्यासाठी आपल्याला लॉगिन करणे आवश्यक आहे.',
    cannot_post_empty_comment: 'टिप्पणी रिक्त असू शकत नाही.',
    comment_posted: 'टिप्पणी पोस्ट केली!',
    error_posting_comment: 'टिप्पणी पोस्ट करताना त्रुटी.',
    // Profile Page
    login_or_signup: 'लॉगिन करा किंवा साइन अप करा',
    enter_mobile_for_otp: 'OTP मिळवण्यासाठी तुमचा मोबाईल नंबर टाका.',
    full_name: 'पूर्ण नाव',
    enter_full_name: 'तुमचे पूर्ण नाव टाका',
    mobile_number: 'मोबाईल नंबर',
    enter_mobile_number: 'तुमचा १०-अंकी मोबाईल नंबर टाका',
    send_otp: 'ओटीपी पाठवा',
    my_profile: 'माझे प्रोफाइल',
    view_manage_account: 'तुमच्या खात्याचे तपशील पहा आणि व्यवस्थापित करा.',
    name: 'नाव',
    state: 'राज्य',
    select_state: 'तुमचे राज्य निवडा',
    district: 'जिल्हा',
    select_district: 'तुमचा जिल्हा निवडा',
    village_town: 'गाव / शहर',
    enter_village_town: 'तुमच्या गावाचे किंवा शहराचे नाव टाका',
    save_changes: 'बदल जतन करा',
    log_out: 'लॉग आउट',
    profile_updated_title: 'प्रोफाइल अद्यतनित केले',
    profile_updated_description: 'तुमचे प्रोफाइल यशस्वीरित्या जतन केले आहे.',
    could_not_save_profile: 'प्रोफाइल जतन करू शकलो नाही.',
    login_failed: 'लॉगिन अयशस्वी',
    login_failed_description: 'तुम्हाला साइन इन करू शकलो नाही. कृपया पुन्हा प्रयत्न करा.',
    // Settings Page
    choose_language: 'ॲपसाठी तुमची पसंतीची भाषा निवडा.',
    notifications: 'सूचना',
    enable_notifications: 'महत्वाच्या सूचनांसाठी सूचना सक्षम करा.',
    enable_notifications_button: 'सूचना सक्षम करा',
    // Assistant Page
    ai_farming_assistant: 'एआय शेती सहाय्यक',
    ask_me_anything: 'मला शेतीबद्दल काहीही विचारा!',
    ask_about_crops: 'पिके, माती किंवा कीटकांबद्दल विचारा...',
    assistant_can_mistake: 'किसान-एआय चुका करू शकतो. महत्त्वाची माहिती तपासण्याचा विचार करा.',
    // Voice Assistant
    voice_assistant_title: 'आवाज सहाय्यक',
    listening: 'ऐकत आहे...',
    processing: 'प्रक्रिया होत आहे...',
    ask_a_question: 'शेतीबद्दल प्रश्न विचारा',
    // Plant Doctor
    plant_doctor_description: 'तुमच्या वनस्पतीचा फोटो काढा किंवा अपलोड करा आणि AI निदानासाठी व्हॉइस नोट जोडा.',
    step_1_image: '१. एक प्रतिमा द्या',
    use_camera_or_upload: 'सुरू करण्यासाठी तुमचा कॅमेरा वापरा किंवा एक प्रतिमा अपलोड करा.',
    camera_access_denied_title: 'कॅमेरा प्रवेश नाकारला',
    camera_access_denied_description: 'ही सुविधा वापरण्यासाठी कृपया तुमच्या ब्राउझर सेटिंग्जमध्ये कॅमेरा परवानग्या सक्षम करा.',
    capture_photo: 'फोटो काढा',
    use_camera: 'कॅमेरा वापरा',
    upload_image: 'प्रतिमा अपलोड करा',
    step_2_voice_note: '२. व्हॉइस नोट जोडा (पर्यायी)',
    voice_note_placeholder: 'तुमची लिप्यंतरित व्हॉइस नोट येथे दिसेल...',
    get_diagnosis: 'निदान मिळवा',
    diagnosing: 'निदान होत आहे...',
    new_diagnosis: 'नवीन निदान सुरू करा',
    plant_diagnosis_report: 'वनस्पती निदान अहवाल',
    confidence: 'आत्मविश्वास',
    quick_summary: 'द्रुत सारांश',
    identification: 'ओळख',
    primary_species: 'प्राथमिक प्रजाती',
    could_not_identify: 'वनस्पती प्रजाती ओळखू शकलो नाही.',
    diagnosis: 'निदान',
    severity: 'તીવ્રતા',
    likelihood: 'शक्यता',
    evidence: 'पुरावा',
    no_issues_diagnosed: 'कोणत्याही विशिष्ट समस्येचे निदान झाले नाही.',
    recommendations: 'शिफारसी',
    cultural_ipm: 'सांस्कृतिक आणि IPM',
    organic_biological: 'सेंद्रिय/जैविक',
    image_quality: 'प्रतिमा गुणवत्ता',
    quality: 'गुणवत्ता',
    suggestions: 'सूचना',
    disease: 'रोग',
    pest: 'कीड',
    nutrient: 'पोषक तत्व',
    physiological: 'शारीरिक',
    camera_not_supported_title: 'कॅमेरा समर्थित नाही',
    camera_not_supported_description: 'तुमचा ब्राउझर कॅमेरा प्रवेशाचे समर्थन करत नाही.',
    browser_not_supported_title: 'ब्राउझर समर्थित नाही',
    browser_not_supported_description: 'तुमचा ब्राउझर व्हॉइस रेकग्निशनला सपोर्ट करत नाही.',
    no_image_title: 'प्रतिमा नाही',
    no_image_description: 'कृपया प्रथम एक प्रतिमा प्रदान करा.',
    diagnosis_failed_title: 'निदान अयशस्वी',
    diagnosis_failed_description: 'वनस्पतीचे विश्लेषण करताना त्रुटी आली. कृपया पुन्हा प्रयत्न करा.',
  },
  ta: {
    welcome: 'வரவேற்பு',
    settings: 'அமைப்புகள்',
    language: 'மொழி',
    post: 'பதிவு செய்',
    home: 'முகப்பு',
    ai_assistant: 'AI உதவியாளர்',
    plant_doctor: 'தாவர மருத்துவர்',
    market: 'சந்தை',
    community: 'சமூகம்',
    profile: 'சுயவிவரம்',
    welcome_to_kisanai: 'கிசான்ஏஐ-க்கு வரவேற்கிறோம்',
    welcome_message: 'வணக்கம், {{name}}!',
    smart_farming_partner: 'ஒரு சிறந்த அறுவடைக்கு உங்கள் έξυπனான விவசாய கூட்டாளி.',
    quick_actions: 'விரைவு நடவடிக்கைகள்',
    quick_links: 'விரைவு இணைப்புகள்',
    get_farming_advice: 'விவசாய ஆலோசனை பெறுங்கள்',
    market_prices: 'சந்தை விலைகள்',
    check_crop_prices: 'பயிர் விலைகளை சரிபார்க்கவும்',
    connect_with_farmers: 'விவசாயிகளுடன் இணையுங்கள்',
    customize_your_app: 'உங்கள் பயன்பாட்டைத் தனிப்பயனாக்குங்கள்',
    daily_tip: 'தினசரி உதவிக்குறிப்பு',
    daily_tip_content: 'உங்கள் வயல்களுக்கு நீர்ப்பாசனம் செய்வதற்கு முன் மண் ஈரப்பதத்தைச் சரிபார்க்கவும். அதிகப்படியான నీటిపారుదల తక్కువ నీటిపారుదల వలె హానికరం.',
    voice_assistant: 'குரல் உதவியாளர்',
    current_weather: 'தற்போதைய வானிலை',
    weather_forecast: 'வானிலை முன்னறிவிப்பு',
    today: 'இன்று',
    weather_error: 'வானிலை பிழை',
    humidity: 'ஈரப்பதம்',
    wind: 'காற்று',
    location_access_denied: 'இடத்திற்கான அணுகல் மறுக்கப்பட்டது',
    fallback_location_weather: 'வானிலைக்காக இயல்புநிலை இருப்பிடத்திற்குத் திரும்புகிறது.',
    latest_prices: 'பல்வேறு சந்தைகளிலிருந்து சமீபத்திய விவசாயப் பொருட்களின் விலைகள்.',
    showing_markets_near: 'அருகிலுள்ள சந்தைகளைக் காட்டுகிறது',
    crop: 'பயிர்',
    price_per_unit: 'விலை (ஒரு அலகுக்கு)',
    trend: 'போக்கு',
    last_updated: 'கடைசியாகப் புதுப்பிக்கப்பட்டது',
    community_feed: 'சமூக ஊட்டம்',
    create_a_post: 'ஒரு இடுகையை உருவாக்கவும்',
    whats_on_your_mind: 'உங்கள் மனதில் என்ன இருக்கிறது, விவசாயி?',
    post_not_found: 'இடுகை கிடைக்கவில்லை',
    back_to_community: 'சமூகத்திற்குத் திரும்பு',
    likes: 'விருப்பங்கள்',
    comments: 'கருத்துகள்',
    leave_a_comment: 'ஒரு கருத்தைச் சொல்லுங்கள்',
    write_your_comment: 'உங்கள் கருத்தை எழுதுங்கள்...',
    comment: 'கருத்து',
    reply: 'பதில்',
    reply_to: 'பதிலளிக்கவும்',
    no_comments_yet: 'இன்னும் கருத்துகள் எதுவும் இல்லை. கருத்து தெரிவிக்கும் முதல் நபராக இருங்கள்!',
    login_to_post: 'உள்நுழைவு தேவை',
    login_to_post_description: 'ஒரு இடுகையை உருவாக்க நீங்கள் உள்நுழைந்திருக்க வேண்டும்.',
    cannot_post_empty: 'இடுகையின் உள்ளடக்கம் காலியாக இருக்க முடியாது.',
    post_created: 'இடுகை வெற்றிகரமாக உருவாக்கப்பட்டது!',
    error_creating_post: 'இடுகையை உருவாக்கும்போது பிழை.',
    login_to_comment: 'உள்நுழைவு தேவை',
    login_to_comment_desc: 'கருத்து தெரிவிக்க நீங்கள் உள்நுழைந்திருக்க வேண்டும்.',
    cannot_post_empty_comment: 'கருத்து காலியாக இருக்க முடியாது.',
    comment_posted: 'கருத்து பதிவிடப்பட்டது!',
    error_posting_comment: 'கருத்தைப் பதிவிடும்போது பிழை.',
    login_or_signup: 'உள்நுழையவும் அல்லது பதிவு செய்யவும்',
    enter_mobile_for_otp: 'OTP பெற உங்கள் மொபைல் எண்ணை உள்ளிடவும்.',
    full_name: 'முழு பெயர்',
    enter_full_name: 'உங்கள் முழு பெயரை உள்ளிடவும்',
    mobile_number: 'மொபைல் எண்',
    enter_mobile_number: 'உங்கள் 10 இலக்க மொபைல் எண்ணை உள்ளிடவும்',
    send_otp: 'OTP அனுப்பவும்',
    my_profile: 'எனது சுயவிவரம்',
    view_manage_account: 'உங்கள் கணக்கு விவரங்களைக் கண்டு நிர்வகிக்கவும்.',
    name: 'பெயர்',
    state: 'மாநிலம்',
    select_state: 'உங்கள் மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
    district: 'மாவட்டம்',
    select_district: 'உங்கள் மாவட்டத்தைத் தேர்ந்தெடுக்கவும்',
    village_town: 'கிராமம் / நகரம்',
    enter_village_town: 'உங்கள் கிராமம் அல்லது நகரத்தின் பெயரை உள்ளிடவும்',
    save_changes: 'மாற்றங்களைச் சேமிக்கவும்',
    log_out: 'வெளியேறு',
    profile_updated_title: 'சுயவிவரம் புதுப்பிக்கப்பட்டது',
    profile_updated_description: 'உங்கள் சுயவிவரம் வெற்றிகரமாக சேமிக்கப்பட்டது.',
    could_not_save_profile: 'சுயவிவரத்தைச் சேமிக்க முடியவில்லை.',
    login_failed: 'உள்நுழைவு தோல்வியுற்றது',
    login_failed_description: 'உங்களை உள்நுழைய முடியவில்லை. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
    choose_language: 'பயன்பாட்டிற்கு உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்.',
    notifications: 'அறிவிப்புகள்',
    enable_notifications: 'முக்கியமான எச்சரிக்கைகளுக்கு அறிவிப்புகளை இயக்கவும்.',
    enable_notifications_button: 'அறிவிப்புகளை இயக்கு',
    ai_farming_assistant: 'AI விவசாய உதவியாளர்',
    ask_me_anything: 'விவசாயம் பற்றி என்னிடம் எதுவும் கேளுங்கள்!',
    ask_about_crops: 'பயிர்கள், மண் அல்லது பூச்சிகள் பற்றி கேளுங்கள்...',
    assistant_can_mistake: 'கிசான்ஏஐ தவறுகள் செய்யலாம். முக்கியமான தகவல்களைச் சரிபார்க்கவும்.',
    voice_assistant_title: 'குரல் உதவியாளர்',
    listening: 'கேட்டுக்கொண்டிருக்கிறது...',
    processing: 'செயலாக்கப்படுகிறது...',
    ask_a_question: 'விவசாயம் பற்றி ஒரு கேள்வி கேளுங்கள்',
    plant_doctor_description: 'ஒரு AI நோயறிதலுக்காக உங்கள் தாவரத்தின் புகைப்படத்தைப் பிடிக்கவும் அல்லது பதிவேற்றவும் மற்றும் ஒரு குரல் குறிப்பைச் சேர்க்கவும்.',
    step_1_image: '1. ஒரு படத்தை வழங்கவும்',
    use_camera_or_upload: 'தொடங்க உங்கள் கேமராவைப் பயன்படுத்தவும் அல்லது ஒரு படத்தைப் பதிவேற்றவும்.',
    camera_access_denied_title: 'கேமரா அணுகல் மறுக்கப்பட்டது',
    camera_access_denied_description: 'இந்த அம்சத்தைப் பயன்படுத்த, உங்கள் உலாவி அமைப்புகளில் கேமரா அனுமதிகளை இயக்கவும்.',
    capture_photo: 'புகைப்படம் எடுக்கவும்',
    use_camera: 'கேமராவைப் பயன்படுத்தவும்',
    upload_image: 'படத்தைப் பதிவேற்றவும்',
    step_2_voice_note: '2. ஒரு குரல் குறிப்பைச் சேர்க்கவும் (விருப்பத்தேர்வு)',
    voice_note_placeholder: 'உங்கள் படியெடுத்த குரல் குறிப்பு இங்கே தோன்றும்...',
    get_diagnosis: 'நோயறிதலைப் பெறுங்கள்',
    diagnosing: 'நோயறிதல்...',
    new_diagnosis: 'புதிய நோயறிதலைத் தொடங்குங்கள்',
    plant_diagnosis_report: 'தாவர நோயறிதல் அறிக்கை',
    confidence: 'நம்பிக்கை',
    quick_summary: 'விரைவு சுருக்கம்',
    identification: 'அடையாளம்',
    primary_species: 'முதன்மை இனங்கள்',
    could_not_identify: 'தாவர இனங்களை அடையாளம் காண முடியவில்லை.',
    diagnosis: 'நோயறிதல்',
    severity: 'கடுமை',
    likelihood: 'சாத்தியம்',
    evidence: 'சான்றுகள்',
    no_issues_diagnosed: 'குறிப்பிட்ட சிக்கல்கள் எதுவும் கண்டறியப்படவில்லை.',
    recommendations: 'பரிந்துரைகள்',
    cultural_ipm: 'கலாச்சார மற்றும் IPM',
    organic_biological: 'கரிம/உயிரியல்',
    image_quality: 'படத்தின் தரம்',
    quality: 'தரம்',
    suggestions: 'பரிந்துரைகள்',
    disease: 'நோய்',
    pest: 'பூச்சி',
    nutrient: 'ஊட்டச்சத்து',
    physiological: 'உடலியல்',
    camera_not_supported_title: 'கேமரா ஆதரிக்கப்படவில்லை',
    camera_not_supported_description: 'உங்கள் உலாவி கேமரா அணுகலை ஆதரிக்கவில்லை.',
    browser_not_supported_title: 'உலாவி ஆதரிக்கப்படவில்லை',
    browser_not_supported_description: 'உங்கள் உலாவி குரல் அங்கீகாரத்தை ஆதரிக்கவில்லை.',
    no_image_title: 'படம் இல்லை',
    no_image_description: 'முதலில் ஒரு படத்தை வழங்கவும்.',
    diagnosis_failed_title: 'நோயறிதல் தோல்வியுற்றது',
    diagnosis_failed_description: 'தாவரத்தை பகுப்பாய்வு செய்யும் போது ஒரு பிழை ஏற்பட்டது. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
  },
  te: {
    welcome: 'స్వాగతం',
    settings: 'సెట్టింగ్‌లు',
    language: 'భాష',
    post: 'పోస్ట్ చేయండి',
    home: 'హోమ్',
    ai_assistant: 'AI సహాయకుడు',
    plant_doctor: 'మొక్కల డాక్టర్',
    market: 'మార్కెట్',
    community: 'సంఘం',
    profile: 'ప్రొఫైల్',
    welcome_to_kisanai: 'కిసాన్‌ఏఐకి స్వాగతం',
    welcome_message: 'నమస్కారం, {{name}}!',
    smart_farming_partner: 'ఒక గొప్ప పంట కోసం మీ స్మార్ట్ వ్యవసాయ భాగస్వామి.',
    quick_actions: 'త్వరిత చర్యలు',
    quick_links: 'త్వరిత లింకులు',
    get_farming_advice: 'వ్యవసాయ సలహా పొందండి',
    market_prices: 'మార్కెట్ ధరలు',
    check_crop_prices: 'పంట ధరలను తనిఖీ చేయండి',
    connect_with_farmers: 'రైతులతో కనెక్ట్ అవ్వండి',
    customize_your_app: 'మీ అనువర్తనాన్ని అనుకూలీకరించండి',
    daily_tip: 'రోజువారీ చిట్కా',
    daily_tip_content: 'మీ పొలాలకు నీరు పెట్టే ముందు నేల తేమను తనిఖీ చేయండి. ఎక్కువ నీరు పెట్టడం కూడా తక్కువ నీరు పెట్టడం అంత హానికరం.',
    voice_assistant: 'వాయిస్ అసిస్టెంట్',
    current_weather: 'ప్రస్తుత వాతావరణం',
    weather_forecast: 'వాతావరణ సూచన',
    today: 'ఈ రోజు',
    weather_error: 'వాతావరణ లోపం',
    humidity: 'తేమ',
    wind: 'గాలి',
    location_access_denied: 'స్థాన ప్రాప్యత నిరాకరించబడింది',
    fallback_location_weather: 'వాతావరణం కోసం డిఫాల్ట్ స్థానానికి తిరిగి వెళుతోంది.',
    latest_prices: 'వివిధ మార్కెట్ల నుండి తాజా వ్యవసాయ వస్తువుల ధరలు.',
    showing_markets_near: 'దగ్గరలోని మార్కెట్లను చూపుతోంది',
    crop: 'పంట',
    price_per_unit: 'ధర (ఒక యూనిట్‌కు)',
    trend: 'ట్రెండ్',
    last_updated: 'చివరిగా నవీకరించబడింది',
    community_feed: 'సంఘం ఫీడ్',
    create_a_post: 'ఒక పోస్ట్‌ను సృష్టించండి',
    whats_on_your_mind: 'మీ మనస్సులో ఏముంది, రైతు?',
    post_not_found: 'పోస్ట్ కనుగొనబడలేదు',
    back_to_community: 'సంఘానికి తిరిగి వెళ్లండి',
    likes: 'ఇష్టాలు',
    comments: 'వ్యాఖ్యలు',
    leave_a_comment: 'ఒక వ్యాఖ్యను ఇవ్వండి',
    write_your_comment: 'మీ వ్యాఖ్యను వ్రాయండి...',
    comment: 'వ్యాఖ్య',
    reply: 'సమాధానం',
    reply_to: 'కి సమాధానం ఇవ్వండి',
    no_comments_yet: 'ఇంకా వ్యాఖ్యలు ఏవీ లేవు. వ్యాఖ్యానించిన మొదటి వ్యక్తి అవ్వండి!',
    login_to_post: 'లాగిన్ అవసరం',
    login_to_post_description: 'ఒక పోస్ట్‌ను సృష్టించడానికి మీరు లాగిన్ అయి ఉండాలి.',
    cannot_post_empty: 'పోస్ట్ కంటెంట్ ఖాళీగా ఉండకూడదు.',
    post_created: 'పోస్ట్ విజయవంతంగా సృష్టించబడింది!',
    error_creating_post: 'పోస్ట్‌ను సృష్టించేటప్పుడు లోపం.',
    login_to_comment: 'లాగిన్ అవసరం',
    login_to_comment_desc: 'వ్యాఖ్యానించడానికి మీరు లాగిన్ అయి ఉండాలి.',
    cannot_post_empty_comment: 'వ్యాఖ్య ఖాళీగా ఉండకూడదు.',
    comment_posted: 'వ్యాఖ్య పోస్ట్ చేయబడింది!',
    error_posting_comment: 'వ్యాఖ్యను పోస్ట్ చేసేటప్పుడు లోపం.',
    login_or_signup: 'లాగిన్ లేదా సైన్ అప్ చేయండి',
    enter_mobile_for_otp: 'OTP స్వీకరించడానికి మీ మొబైల్ నంబర్‌ను నమోదు చేయండి.',
    full_name: 'పూర్తి పేరు',
    enter_full_name: 'మీ పూర్తి పేరును నమోదు చేయండి',
    mobile_number: 'మొబైల్ నంబర్',
    enter_mobile_number: 'మీ 10-అంకెల మొబైల్ నంబర్‌ను నమోదు చేయండి',
    send_otp: 'OTP పంపండి',
    my_profile: 'నా ప్రొఫైల్',
    view_manage_account: 'మీ ఖాతా వివరాలను వీక్షించండి మరియు నిర్వహించండి.',
    name: 'పేరు',
    state: 'రాష్ట్రం',
    select_state: 'మీ రాష్ట్రాన్ని ఎంచుకోండి',
    district: 'జిల్లా',
    select_district: 'మీ జిల్లాను ఎంచుకోండి',
    village_town: 'గ్రామం / పట్టణం',
    enter_village_town: 'మీ గ్రామం లేదా పట్టణం పేరును నమోదు చేయండి',
    save_changes: 'మార్పులను సేవ్ చేయండి',
    log_out: 'లాగ్ అవుట్',
    profile_updated_title: 'ప్రొఫైల్ నవీకరించబడింది',
    profile_updated_description: 'మీ ప్రొఫైల్ విజయవంతంగా సేవ్ చేయబడింది.',
    could_not_save_profile: 'ప్రొఫైల్‌ను సేవ్ చేయడం సాధ్యం కాలేదు.',
    login_failed: 'లాగిన్ విఫలమైంది',
    login_failed_description: 'మిమ్మల్ని సైన్ ఇన్ చేయడం సాధ్యం కాలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.',
    choose_language: 'అనువర్తనం కోసం మీ ప్రాధాన్య భాషను ఎంచుకోండి.',
    notifications: 'నోటిఫికేషన్‌లు',
    enable_notifications: 'ముఖ్యమైన హెచ్చరికల కోసం నోటిఫికేషన్‌లను ప్రారంభించండి.',
    enable_notifications_button: 'నోటిఫికేషన్‌లను ప్రారంభించు',
    ai_farming_assistant: 'AI వ్యవసాయ సహాయకుడు',
    ask_me_anything: 'వ్యవసాయం గురించి నన్ను ఏదైనా అడగండి!',
    ask_about_crops: 'పంటలు, నేల లేదా తెగుళ్ళ గురించి అడగండి...',
    assistant_can_mistake: 'కిసాన్‌ఏఐ తప్పులు చేయవచ్చు. ముఖ్యమైన సమాచారాన్ని తనిఖీ చేయడాన్ని పరిగణించండి.',
    voice_assistant_title: 'వాయిస్ అసిస్టెంట్',
    listening: 'వింటున్నాను...',
    processing: 'ప్రాసెస్ చేస్తోంది...',
    ask_a_question: 'వ్యవసాయం గురించి ఒక ప్రశ్న అడగండి',
    plant_doctor_description: 'ఒక AI నిర్ధారణ కోసం మీ మొక్క యొక్క ఫోటోను తీయండి లేదా అప్‌లోడ్ చేయండి మరియు వాయిస్ నోట్‌ను జోడించండి.',
    step_1_image: '1. ఒక చిత్రాన్ని అందించండి',
    use_camera_or_upload: 'ప్రారంభించడానికి మీ కెమెరాను ఉపయోగించండి లేదా ఒక చిత్రాన్ని అప్‌లోడ్ చేయండి.',
    camera_access_denied_title: 'కెమెరా యాక్సెస్ నిరాకరించబడింది',
    camera_access_denied_description: 'ఈ లక్షణాన్ని ఉపయోగించడానికి దయచేసి మీ బ్రౌజర్ సెట్టింగ్‌లలో కెమెరా అనుమతులను ప్రారంభించండి.',
    capture_photo: 'ఫోటో తీయండి',
    use_camera: 'కెమెరాను ఉపయోగించండి',
    upload_image: 'చిత్రాన్ని అప్‌లోడ్ చేయండి',
    step_2_voice_note: '2. ఒక వాయిస్ నోట్‌ను జోడించండి (ఐచ్ఛికం)',
    voice_note_placeholder: 'మీ లిప్యంతరీకరించిన వాయిస్ నోట్ ఇక్కడ కనిపిస్తుంది...',
    get_diagnosis: 'నిర్ధారణ పొందండి',
    diagnosing: 'నిర్ధారణ చేస్తోంది...',
    new_diagnosis: 'కొత్త నిర్ధారణను ప్రారంభించండి',
    plant_diagnosis_report: 'మొక్కల నిర్ధారణ నివేదిక',
    confidence: 'ఆత్మవిశ్వాసం',
    quick_summary: 'త్వరిత సారాంశం',
    identification: 'గుర్తింపు',
    primary_species: 'ప్రాధమిక జాతులు',
    could_not_identify: 'మొక్కల జాతులను గుర్తించడం సాధ్యం కాలేదు.',
    diagnosis: 'నిర్ధారణ',
    severity: 'తీవ్రత',
    likelihood: 'సంభావ్యత',
    evidence: 'సాక్ష్యం',
    no_issues_diagnosed: 'ప్రత్యేక సమస్యలు ఏవీ నిర్ధారించబడలేదు.',
    recommendations: 'సిఫార్సులు',
    cultural_ipm: 'సాంస్కృతిక & IPM',
    organic_biological: 'సేంద్రీయ/జీవ',
    image_quality: 'చిత్ర నాణ్యత',
    quality: 'నాణ్యత',
    suggestions: 'సూచనలు',
    disease: 'వ్యాధి',
    pest: 'తెగులు',
    nutrient: 'పోషకం',
    physiological: 'శారీరక',
    camera_not_supported_title: 'కెమెరా మద్దతు లేదు',
    camera_not_supported_description: 'మీ బ్రౌజర్ కెమెరా యాక్సెస్‌కు మద్దతు ఇవ్వదు.',
    browser_not_supported_title: 'బ్రౌజర్ మద్దతు లేదు',
    browser_not_supported_description: 'మీ బ్రౌజర్ వాయిస్ రికగ్నిషన్‌కు మద్దతు ఇవ్వదు.',
    no_image_title: 'చిత్రం లేదు',
    no_image_description: 'దయచేసి మొదట ఒక చిత్రాన్ని అందించండి.',
    diagnosis_failed_title: 'నిర్ధారణ విఫలమైంది',
    diagnosis_failed_description: 'మొక్కను విశ్లేషించేటప్పుడు లోపం సంభవించింది. దయచేసి మళ్లీ ప్రయత్నించండి.',
  },
  kn: {
    welcome: 'ಸ್ವಾಗತ',
    settings: 'ಸಂಯೋಜನೆಗಳು',
    language: 'ಭಾಷೆ',
    post: 'ಪೋಸ್ಟ್ ಮಾಡಿ',
    home: 'ಮನೆ',
    ai_assistant: 'AI ಸಹಾಯಕ',
    plant_doctor: 'ಸಸ್ಯ ವೈದ್ಯ',
    market: 'ಮಾರುಕಟ್ಟೆ',
    community: 'ಸಮುದಾಯ',
    profile: 'ಪ್ರೊಫೈಲ್',
    welcome_to_kisanai: 'ಕಿಸಾನ್‌ಎಐಗೆ ಸ್ವಾಗತ',
    welcome_message: 'ನಮಸ್ಕಾರ, {{name}}!',
    smart_farming_partner: 'ಉತ್ತಮ ಸುಗ್ಗಿಗಾಗಿ ನಿಮ್ಮ ಸ್ಮಾರ್ಟ್ ಕೃಷಿ ಪಾಲುದಾರ.',
    quick_actions: 'ತ್ವರಿತ ಕ್ರಮಗಳು',
    quick_links: 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು',
    get_farming_advice: 'ಕೃಷಿ ಸಲಹೆ ಪಡೆಯಿರಿ',
    market_prices: 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು',
    check_crop_prices: 'ಬೆಳೆ ಬೆಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
    connect_with_farmers: 'ರೈತರೊಂದಿಗೆ ಸಂಪರ್ಕ ಸಾಧಿಸಿ',
    customize_your_app: 'ನಿಮ್ಮ ಅಪ್ಲಿಕೇಶನ್ ಅನ್ನು ಕಸ್ಟಮೈಸ್ ಮಾಡಿ',
    daily_tip: 'ದೈನಂದಿನ ಸಲಹೆ',
    daily_tip_content: 'ನಿಮ್ಮ ಹೊಲಗಳಿಗೆ ನೀರುಣಿಸುವ ಮೊದಲು ಮಣ್ಣಿನ ತೇವಾಂಶವನ್ನು ಪರೀಕ್ಷಿಸಿ. ಹೆಚ್ಚು ನೀರುಣಿಸುವುದು ಕಡಿಮೆ ನೀರುಣಿಸುವಷ್ಟೇ ಹಾನಿಕಾರಕ.',
    voice_assistant: 'ಧ್ವನಿ ಸಹಾಯಕ',
    current_weather: 'ಪ್ರಸ್ತುತ ಹವಾಮಾನ',
    weather_forecast: 'ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ',
    today: 'ಇಂದು',
    weather_error: 'ಹವಾಮಾನ ದೋಷ',
    humidity: 'ತೇವಾಂಶ',
    wind: 'ಗಾಳಿ',
    location_access_denied: 'ಸ್ಥಳ ಪ್ರವೇಶವನ್ನು ನಿರಾಕರಿಸಲಾಗಿದೆ',
    fallback_location_weather: 'ಹವಾಮಾನಕ್ಕಾಗಿ ಡೀಫಾಲ್ಟ್ ಸ್ಥಳಕ್ಕೆ ಹಿಂತಿರುಗಲಾಗುತ್ತಿದೆ.',
    latest_prices: 'ವಿವಿಧ ಮಾರುಕಟ್ಟೆಗಳಿಂದ ಇತ್ತೀಚಿನ ಕೃಷಿ ಸರಕುಗಳ ಬೆಲೆಗಳು.',
    showing_markets_near: 'ಹತ್ತಿರದ ಮಾರುಕಟ್ಟೆಗಳನ್ನು ತೋರಿಸುತ್ತಿದೆ',
    crop: 'ಬೆಳೆ',
    price_per_unit: 'ಬೆಲೆ (ಪ್ರತಿ ಘಟಕಕ್ಕೆ)',
    trend: 'ಪ್ರವೃತ್ತಿ',
    last_updated: 'ಕೊನೆಯದಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ',
    community_feed: 'ಸಮುದಾಯ ಫೀಡ್',
    create_a_post: 'ಪೋಸ್ಟ್ ರಚಿಸಿ',
    whats_on_your_mind: 'ನಿಮ್ಮ ಮನಸ್ಸಿನಲ್ಲಿ ಏನಿದೆ, ರೈತ?',
    post_not_found: 'ಪೋಸ್ಟ್ ಕಂಡುಬಂದಿಲ್ಲ',
    back_to_community: 'ಸಮುದಾಯಕ್ಕೆ ಹಿಂತಿರುಗಿ',
    likes: 'ಇಷ್ಟಗಳು',
    comments: 'ಪ್ರತಿಕ್ರಿಯೆಗಳು',
    leave_a_comment: 'ಪ್ರತಿಕ್ರಿಯೆ ನೀಡಿ',
    write_your_comment: 'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಬರೆಯಿರಿ...',
    comment: 'ಪ್ರತಿಕ್ರಿಯೆ',
    reply: 'ಉತ್ತರ',
    reply_to: 'ಗೆ ಉತ್ತರಿಸಿ',
    no_comments_yet: 'ಇನ್ನೂ ಯಾವುದೇ ಪ್ರತಿಕ್ರಿಯೆಗಳಿಲ್ಲ. ಪ್ರತಿಕ್ರಿಯಿಸಿದ ಮೊದಲ ವ್ಯಕ್ತಿಯಾಗಿ!',
    login_to_post: 'ಲಾಗಿನ್ ಅಗತ್ಯವಿದೆ',
    login_to_post_description: 'ಪೋಸ್ಟ್ ರಚಿಸಲು ನೀವು ಲಾಗಿನ್ ಆಗಿರಬೇಕು.',
    cannot_post_empty: 'ಪೋಸ್ಟ್ ವಿಷಯ ಖಾಲಿಯಾಗಿರಬಾರದು.',
    post_created: 'ಪೋಸ್ಟ್ ಯಶಸ್ವಿಯಾಗಿ ರಚಿಸಲಾಗಿದೆ!',
    error_creating_post: 'ಪೋಸ್ಟ್ ರಚಿಸುವಾಗ ದೋಷ.',
    login_to_comment: 'ಲಾಗಿನ್ ಅಗತ್ಯವಿದೆ',
    login_to_comment_desc: 'ಪ್ರತಿಕ್ರಿಯಿಸಲು ನೀವು ಲಾಗಿನ್ ಆಗಿರಬೇಕು.',
    cannot_post_empty_comment: 'ಪ್ರತಿಕ್ರಿಯೆ ಖಾಲಿಯಾಗಿರಬಾರದು.',
    comment_posted: 'ಪ್ರತಿಕ್ರಿಯೆ ಪೋಸ್ಟ್ ಮಾಡಲಾಗಿದೆ!',
    error_posting_comment: 'ಪ್ರತಿಕ್ರಿಯೆ ಪೋಸ್ಟ್ ಮಾಡುವಾಗ ದೋಷ.',
    login_or_signup: 'ಲಾಗಿನ್ ಅಥವಾ ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    enter_mobile_for_otp: 'ಒಟಿಪಿ ಸ್ವೀಕರಿಸಲು ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ.',
    full_name: 'ಪೂರ್ಣ ಹೆಸರು',
    enter_full_name: 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
    mobile_number: 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    enter_mobile_number: 'ನಿಮ್ಮ 10-ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    send_otp: 'ಒಟಿಪಿ ಕಳುಹಿಸಿ',
    my_profile: 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    view_manage_account: 'ನಿಮ್ಮ ಖಾತೆ ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ ಮತ್ತು ನಿರ್ವಹಿಸಿ.',
    name: 'ಹೆಸರು',
    state: 'ರಾಜ್ಯ',
    select_state: 'ನಿಮ್ಮ ರಾಜ್ಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    district: 'ಜಿಲ್ಲೆ',
    select_district: 'ನಿಮ್ಮ ಜಿಲ್ಲೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    village_town: 'ಗ್ರಾಮ / ಪಟ್ಟಣ',
    enter_village_town: 'ನಿಮ್ಮ ಗ್ರಾಮ ಅಥವಾ ಪಟ್ಟಣದ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
    save_changes: 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    log_out: 'ಲಾಗ್ ಔಟ್',
    profile_updated_title: 'ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಲಾಗಿದೆ',
    profile_updated_description: 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ಯಶಸ್ವಿಯಾಗಿ ಉಳಿಸಲಾಗಿದೆ.',
    could_not_save_profile: 'ಪ್ರೊಫೈಲ್ ಉಳಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.',
    login_failed: 'ಲಾಗಿನ್ ವಿಫಲವಾಗಿದೆ',
    login_failed_description: 'ನಿಮ್ಮನ್ನು ಸೈನ್ ಇನ್ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    choose_language: 'ಅಪ್ಲಿಕೇಶನ್‌ಗಾಗಿ ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    enable_notifications: 'ಪ್ರಮುಖ ಎಚ್ಚರಿಕೆಗಳಿಗಾಗಿ ಅಧಿಸೂಚನೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ.',
    enable_notifications_button: 'ಅಧಿಸೂಚನೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ',
    ai_farming_assistant: 'AI ಕೃಷಿ ಸಹಾಯಕ',
    ask_me_anything: 'ಕೃಷಿ ಬಗ್ಗೆ ನನ್ನನ್ನು ಏನು ಬೇಕಾದರೂ ಕೇಳಿ!',
    ask_about_crops: 'ಬೆಳೆಗಳು, ಮಣ್ಣು, ಅಥವಾ ಕೀಟಗಳ ಬಗ್ಗೆ ಕೇಳಿ...',
    assistant_can_mistake: 'ಕಿಸಾನ್‌ಎಐ ತಪ್ಪುಗಳನ್ನು ಮಾಡಬಹುದು. ಪ್ರಮುಖ ಮಾಹಿತಿಯನ್ನು ಪರಿಶೀಲಿಸುವುದನ್ನು ಪರಿಗಣಿಸಿ.',
    voice_assistant_title: 'ಧ್ವನಿ ಸಹಾಯಕ',
    listening: 'ಕೇಳುತ್ತಿದೆ...',
    processing: 'ಸಂಸ್ಕರಿಸಲಾಗುತ್ತಿದೆ...',
    ask_a_question: 'ಕೃಷಿ ಬಗ್ಗೆ ಪ್ರಶ್ನೆ ಕೇಳಿ',
    plant_doctor_description: 'ನಿಮ್ಮ ಸಸ್ಯದ ಫೋಟೋವನ್ನು ಸೆರೆಹಿಡಿಯಿರಿ ಅಥವಾ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು AI ರೋಗನಿರ್ಣಯಕ್ಕಾಗಿ ಧ್ವನಿ ಟಿಪ್ಪಣಿಯನ್ನು ಸೇರಿಸಿ.',
    step_1_image: '1. ಚಿತ್ರವನ್ನು ಒದಗಿಸಿ',
    use_camera_or_upload: 'ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಕ್ಯಾಮರಾವನ್ನು ಬಳಸಿ ಅಥವಾ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.',
    camera_access_denied_title: 'ಕ್ಯಾಮರಾ ಪ್ರವೇಶವನ್ನು ನಿರಾಕರಿಸಲಾಗಿದೆ',
    camera_access_denied_description: 'ಈ ವೈಶಿಷ್ಟ್ಯವನ್ನು ಬಳಸಲು ದಯವಿಟ್ಟು ನಿಮ್ಮ ಬ್ರೌಸರ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಕ್ಯಾಮರಾ ಅನುಮತಿಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ.',
    capture_photo: 'ಫೋಟೋ ಸೆರೆಹಿಡಿಯಿರಿ',
    use_camera: 'ಕ್ಯಾಮರಾ ಬಳಸಿ',
    upload_image: 'ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    step_2_voice_note: '2. ಧ್ವನಿ ಟಿಪ್ಪಣಿಯನ್ನು ಸೇರಿಸಿ (ಐಚ್ಛಿಕ)',
    voice_note_placeholder: 'ನಿಮ್ಮ ಲಿಪ್ಯಂತರಗೊಂಡ ಧ್ವನಿ ಟಿಪ್ಪಣಿ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ...',
    get_diagnosis: 'ರೋಗನಿರ್ಣಯ ಪಡೆಯಿರಿ',
    diagnosing: 'ರೋಗನಿರ್ಣಯ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    new_diagnosis: 'ಹೊಸ ರೋಗನಿರ್ಣಯವನ್ನು ಪ್ರಾರಂಭಿಸಿ',
    plant_diagnosis_report: 'ಸಸ್ಯ ರೋಗನಿರ್ಣಯ ವರದಿ',
    confidence: 'ವಿಶ್ವಾಸ',
    quick_summary: 'ತ್ವರಿತ ಸಾರಾಂಶ',
    identification: 'ಗುರುತಿಸುವಿಕೆ',
    primary_species: 'ಪ್ರಾಥಮಿಕ ಪ್ರಭೇದ',
    could_not_identify: 'ಸಸ್ಯ ಪ್ರಭೇದವನ್ನು ಗುರುತಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.',
    diagnosis: 'ರೋಗನಿರ್ಣಯ',
    severity: 'ತೀವ್ರತೆ',
    likelihood: 'ಸಂಭವನೀಯತೆ',
    evidence: 'ಸಾಕ್ಷ್ಯ',
    no_issues_diagnosed: 'ಯಾವುದೇ ನಿರ್ದಿಷ್ಟ ಸಮಸ್ಯೆಗಳನ್ನು ಪತ್ತೆಹಚ್ಚಲಾಗಿಲ್ಲ.',
    recommendations: 'ಶಿಫಾರಸುಗಳು',
    cultural_ipm: 'ಸಾಂಸ್ಕೃತಿಕ ಮತ್ತು IPM',
    organic_biological: 'ಸಾವಯವ/ಜೈವಿಕ',
    image_quality: 'ಚಿತ್ರದ ಗುಣಮಟ್ಟ',
    quality: 'ಗುಣಮಟ್ಟ',
    suggestions: 'ಸಲಹೆಗಳು',
    disease: 'ರೋಗ',
    pest: 'ಕೀಟ',
    nutrient: 'ಪೋಷಕಾಂಶ',
    physiological: 'ಶಾರೀರಿಕ',
    camera_not_supported_title: 'ಕ್ಯಾಮರಾ ಬೆಂಬಲಿಸುವುದಿಲ್ಲ',
    camera_not_supported_description: 'ನಿಮ್ಮ ಬ್ರೌಸರ್ ಕ್ಯಾಮರಾ ಪ್ರವೇಶವನ್ನು ಬೆಂಬಲಿಸುವುದಿಲ್ಲ.',
    browser_not_supported_title: 'ಬ್ರೌಸರ್ ಬೆಂಬಲಿಸುವುದಿಲ್ಲ',
    browser_not_supported_description: 'ನಿಮ್ಮ ಬ್ರೌಸರ್ ಧ್ವನಿ ಗುರುತಿಸುವಿಕೆಯನ್ನು ಬೆಂಬಲಿಸುವುದಿಲ್ಲ.',
    no_image_title: 'ಚಿತ್ರವಿಲ್ಲ',
    no_image_description: 'ದಯವಿಟ್ಟು ಮೊದಲು ಚಿತ್ರವನ್ನು ಒದಗಿಸಿ.',
    diagnosis_failed_title: 'ರೋಗನಿರ್ಣಯ ವಿಫಲವಾಗಿದೆ',
    diagnosis_failed_description: 'ಸಸ್ಯವನ್ನು ವಿಶ್ಲೇಷಿಸುವಾಗ ದೋಷ ಸಂಭವಿಸಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
  },
  bn: {
    welcome: 'স্বাগত',
    settings: 'সেটিংস',
    language: 'ভাষা',
    post: 'পোস্ট করুন',
    home: 'হোম',
    ai_assistant: 'এআই সহকারী',
    plant_doctor: 'প্ল্যান্ট ডক্টর',
    market: 'বাজার',
    community: 'সম্প্রদায়',
    profile: 'প্রোফাইল',
    welcome_to_kisanai: 'কিসানএআই-তে স্বাগতম',
    welcome_message: 'নমস্কার, {{name}}!',
    smart_farming_partner: 'একটি সমৃদ্ধ ফসলের জন্য আপনার স্মার্ট চাষ অংশীদার।',
    quick_actions: 'দ্রুত ক্রিয়া',
    quick_links: 'দ্রুত লিঙ্ক',
    get_farming_advice: 'চাষের পরামর্শ নিন',
    market_prices: 'বাজার দর',
    check_crop_prices: 'ফসলের দাম পরীক্ষা করুন',
    connect_with_farmers: 'চাষীদের সাথে সংযোগ স্থাপন করুন',
    customize_your_app: 'আপনার অ্যাপটি কাস্টমাইজ করুন',
    daily_tip: 'দৈনিক টিপ',
    daily_tip_content: 'আপনার জমিতে সেচ দেওয়ার আগে মাটির আর্দ্রতা পরীক্ষা করুন। অতিরিক্ত জল দেওয়া কম জল দেওয়ার মতোই ক্ষতিকর হতে পারে।',
    voice_assistant: 'ভয়েস সহকারী',
    current_weather: 'বর্তমান আবহাওয়া',
    weather_forecast: 'আবহাওয়ার পূর্বাভাস',
    today: 'আজ',
    weather_error: 'আবহাওয়ার ত্রুটি',
    humidity: 'আর্দ্রতা',
    wind: 'বাতাস',
    location_access_denied: 'অবস্থান অ্যাক্সেস অস্বীকার করা হয়েছে',
    fallback_location_weather: 'আবহাওয়ার জন্য ডিফল্ট অবস্থানে ফিরে যাওয়া হচ্ছে।',
    latest_prices: 'বিভিন্ন বাজার থেকে সর্বশেষ কৃষি পণ্যের দাম।',
    showing_markets_near: 'কাছাকাছি বাজার দেখাচ্ছে',
    crop: 'ফসল',
    price_per_unit: 'দাম (প্রতি ইউনিটে)',
    trend: 'প্রবণতা',
    last_updated: 'শেষ আপডেট',
    community_feed: 'সম্প্রদায় ফিড',
    create_a_post: 'একটি পোস্ট তৈরি করুন',
    whats_on_your_mind: 'আপনার মনে কি আছে, কৃষক?',
    post_not_found: 'পোস্ট পাওয়া যায়নি',
    back_to_community: 'সম্প্রদায়ে ফিরে যান',
    likes: 'লাইক',
    comments: 'মন্তব্য',
    leave_a_comment: 'একটি মন্তব্য করুন',
    write_your_comment: 'আপনার মন্তব্য লিখুন...',
    comment: 'মন্তব্য',
    reply: 'উত্তর',
    reply_to: 'কে উত্তর দিন',
    no_comments_yet: 'এখনও কোনো মন্তব্য নেই। প্রথম মন্তব্যকারী হন!',
    login_to_post: 'লগইন প্রয়োজন',
    login_to_post_description: 'একটি পোস্ট তৈরি করতে আপনাকে লগইন করতে হবে।',
    cannot_post_empty: 'পোস্টের বিষয়বস্তু খালি হতে পারে না।',
    post_created: 'পোস্ট সফলভাবে তৈরি করা হয়েছে!',
    error_creating_post: 'পোস্ট তৈরিতে ত্রুটি।',
    login_to_comment: 'লগইন প্রয়োজন',
    login_to_comment_desc: 'মন্তব্য করতে আপনাকে লগইন করতে হবে।',
    cannot_post_empty_comment: 'মন্তব্য খালি হতে পারে না।',
    comment_posted: 'মন্তব্য পোস্ট করা হয়েছে!',
    error_posting_comment: 'মন্তব্য পোস্ট করার সময় ত্রুটি।',
    login_or_signup: 'লগইন বা সাইন আপ করুন',
    enter_mobile_for_otp: 'ওটিপি পেতে আপনার মোবাইল নম্বর লিখুন।',
    full_name: 'পুরো নাম',
    enter_full_name: 'আপনার পুরো নাম লিখুন',
    mobile_number: 'মোবাইল নম্বর',
    enter_mobile_number: 'আপনার ১০-সংখ্যার মোবাইল নম্বর লিখুন',
    send_otp: 'ওটিপি পাঠান',
    my_profile: 'আমার প্রোফাইল',
    view_manage_account: 'আপনার অ্যাকাউন্টের বিবরণ দেখুন এবং পরিচালনা করুন।',
    name: 'নাম',
    state: 'রাজ্য',
    select_state: 'আপনার রাজ্য নির্বাচন করুন',
    district: 'জেলা',
    select_district: 'আপনার জেলা নির্বাচন করুন',
    village_town: 'গ্রাম / শহর',
    enter_village_town: 'আপনার গ্রাম বা শহরের নাম লিখুন',
    save_changes: 'পরিবর্তনগুলি সংরক্ষণ করুন',
    log_out: 'লগ আউট',
    profile_updated_title: 'প্রোফাইল আপডেট করা হয়েছে',
    profile_updated_description: 'আপনার প্রোফাইল সফলভাবে সংরক্ষিত হয়েছে।',
    could_not_save_profile: 'প্রোফাইল সংরক্ষণ করা যায়নি।',
    login_failed: 'লগইন ব্যর্থ হয়েছে',
    login_failed_description: 'আপনাকে সাইন ইন করা যায়নি। অনুগ্রহ করে আবার চেষ্টা করুন।',
    choose_language: 'অ্যাপের জন্য আপনার পছন্দের ভাষা চয়ন করুন।',
    notifications: 'বিজ্ঞপ্তি',
    enable_notifications: 'গুরুত্বপূর্ণ সতর্কতার জন্য বিজ্ঞপ্তি সক্ষম করুন।',
    enable_notifications_button: 'বিজ্ঞপ্তি সক্ষম করুন',
    ai_farming_assistant: 'এআই চাষ সহকারী',
    ask_me_anything: 'চাষাবাদ সম্পর্কে আমাকে কিছু জিজ্ঞাসা করুন!',
    ask_about_crops: 'ফসল, মাটি বা কীটপতঙ্গ সম্পর্কে জিজ্ঞাসা করুন...',
    assistant_can_mistake: 'কিসানএআই ভুল করতে পারে। গুরুত্বপূর্ণ তথ্য পরীক্ষা করার কথা বিবেচনা করুন।',
    voice_assistant_title: 'ভয়েস সহকারী',
    listening: 'শুনছি...',
    processing: 'প্রসেস করা হচ্ছে...',
    ask_a_question: 'চাষাবাদ সম্পর্কে একটি প্রশ্ন জিজ্ঞাসা করুন',
    plant_doctor_description: 'আপনার গাছের একটি ছবি তুলুন বা আপলোড করুন এবং একটি এআই নির্ণয়ের জন্য একটি ভয়েস নোট যোগ করুন।',
    step_1_image: '১. একটি ছবি দিন',
    use_camera_or_upload: 'শুরু করতে আপনার ক্যামেরা ব্যবহার করুন বা একটি ছবি আপলোড করুন।',
    camera_access_denied_title: 'ক্যামেরা অ্যাক্সেস অস্বীকার করা হয়েছে',
    camera_access_denied_description: 'এই বৈশিষ্ট্যটি ব্যবহার করতে আপনার ব্রাউজার সেটিংসে ক্যামেরা অনুমতি সক্ষম করুন।',
    capture_photo: 'ছবি তুলুন',
    use_camera: 'ক্যামেরা ব্যবহার করুন',
    upload_image: 'ছবি আপলোড করুন',
    step_2_voice_note: '২. একটি ভয়েস নোট যোগ করুন (ঐচ্ছিক)',
    voice_note_placeholder: 'আপনার প্রতিলিপিকৃত ভয়েস নোট এখানে প্রদর্শিত হবে...',
    get_diagnosis: 'নির্ণয় পান',
    diagnosing: 'নির্ণয় করা হচ্ছে...',
    new_diagnosis: 'নতুন নির্ণয় শুরু করুন',
    plant_diagnosis_report: 'উদ্ভিদ নির্ণয় প্রতিবেদন',
    confidence: 'আত্মবিশ্বাস',
    quick_summary: 'দ্রুত সারাংশ',
    identification: 'শনাক্তকরণ',
    primary_species: 'প্রাথমিক প্রজাতি',
    could_not_identify: 'উদ্ভিদ প্রজাতি শনাক্ত করা যায়নি।',
    diagnosis: 'নির্ণয়',
    severity: 'গুরুত্ব',
    likelihood: 'সম্ভাবনা',
    evidence: 'প্রমাণ',
    no_issues_diagnosed: 'কোনো নির্দিষ্ট সমস্যা নির্ণয় করা হয়নি।',
    recommendations: 'সুপারিশ',
    cultural_ipm: 'সাংস্কৃতিক এবং আইপিএম',
    organic_biological: 'জৈব/জৈবিক',
    image_quality: 'ছবির গুণমান',
    quality: 'গুণমান',
    suggestions: 'পরামর্শ',
    disease: 'রোগ',
    pest: ' কীটপতঙ্গ',
    nutrient: 'পুষ্টি',
    physiological: 'শারীরবৃত্তীয়',
    camera_not_supported_title: 'ক্যামেরা সমর্থিত নয়',
    camera_not_supported_description: 'আপনার ব্রাউজার ক্যামেরা অ্যাক্সেস সমর্থন করে না।',
    browser_not_supported_title: 'ব্রাউজার সমর্থিত নয়',
    browser_not_supported_description: 'আপনার ব্রাউজার ভয়েস রিকগনিশন সমর্থন করে না।',
    no_image_title: 'ছবি নেই',
    no_image_description: 'অনুগ্রহ করে প্রথমে একটি ছবি দিন।',
    diagnosis_failed_title: 'নির্ণয় ব্যর্থ হয়েছে',
    diagnosis_failed_description: 'উদ্ভিদ বিশ্লেষণ করার সময় একটি ত্রুটি ঘটেছে। অনুগ্রহ করে আবার চেষ্টা করুন।',
  },
  pa: {
    welcome: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    settings: 'ਸੈਟਿੰਗਾਂ',
    language: 'ਭਾਸ਼ਾ',
    post: 'ਪੋਸਟ ਕਰੋ',
    home: 'ਮੁੱਖ',
    ai_assistant: 'ਏਆਈ ਸਹਾਇਕ',
    plant_doctor: 'ਪਲਾਂਟ ਡਾਕਟਰ',
    market: 'ਬਾਜ਼ਾਰ',
    community: 'ਭਾਈਚਾਰਾ',
    profile: 'ਪ੍ਰੋਫਾਈਲ',
    welcome_to_kisanai: 'ਕਿਸਾਨਏਆਈ ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ',
    welcome_message: 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ, {{name}}!',
    smart_farming_partner: 'ਇੱਕ ਅਮੀਰ ਫਸਲ ਲਈ ਤੁਹਾਡਾ ਸਮਾਰਟ ਖੇਤੀਬਾੜੀ ਸਾਥੀ।',
    quick_actions: 'ਤੁਰੰਤ ਕਾਰਵਾਈਆਂ',
    quick_links: 'ਤੁਰੰਤ ਲਿੰਕ',
    get_farming_advice: 'ਖੇਤੀਬਾੜੀ ਸਲਾਹ ਲਵੋ',
    market_prices: 'ਬਾਜ਼ਾਰ ਦੀਆਂ ਕੀਮਤਾਂ',
    check_crop_prices: 'ਫਸਲਾਂ ਦੀਆਂ ਕੀਮਤਾਂ ਦੀ ਜਾਂਚ ਕਰੋ',
    connect_with_farmers: 'ਕਿਸਾਨਾਂ ਨਾਲ ਜੁੜੋ',
    customize_your_app: 'ਆਪਣੀ ਐਪ ਨੂੰ ਅਨੁਕੂਲਿਤ ਕਰੋ',
    daily_tip: 'ਰੋਜ਼ਾਨਾ ਸੁਝਾਅ',
    daily_tip_content: 'ਆਪਣੇ ਖੇਤਾਂ ਨੂੰ ਸਿੰਜਾਈ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਮਿੱਟੀ ਦੀ ਨਮੀ ਦੀ ਜਾਂਚ ਕਰੋ। ਵੱਧ ਪਾਣੀ ਦੇਣਾ ਘੱਟ ਪਾਣੀ ਦੇਣ ਵਾਂਗ ਹੀ ਨੁਕਸਾਨਦੇਹ ਹੋ ਸਕਦਾ ਹੈ।',
    voice_assistant: 'ਆਵਾਜ਼ ਸਹਾਇਕ',
    current_weather: 'ਮੌਜੂਦਾ ਮੌਸਮ',
    weather_forecast: 'ਮੌਸਮ ਦੀ ਭਵਿੱਖਬਾਣੀ',
    today: 'ਅੱਜ',
    weather_error: 'ਮੌਸਮ ਵਿੱਚ ਗਲਤੀ',
    humidity: 'ਨਮੀ',
    wind: 'ਹਵਾ',
    location_access_denied: 'ਸਥਾਨ ਪਹੁੰਚ ਤੋਂ ਇਨਕਾਰ ਕੀਤਾ ਗਿਆ',
    fallback_location_weather: 'ਮੌਸਮ ਲਈ ਡਿਫੌਲਟ ਸਥਾਨ ਤੇ ਵਾਪਸ ਜਾ ਰਿਹਾ ਹੈ।',
    latest_prices: 'ਵੱਖ-ਵੱਖ ਬਾਜ਼ਾਰਾਂ ਤੋਂ ਨਵੀਨਤਮ ਖੇਤੀਬਾੜੀ ਵਸਤਾਂ ਦੀਆਂ ਕੀਮਤਾਂ।',
    showing_markets_near: 'ਨੇੜਲੇ ਬਾਜ਼ਾਰਾਂ ਨੂੰ ਦਿਖਾ ਰਿਹਾ ਹੈ',
    crop: 'ਫਸਲ',
    price_per_unit: 'ਕੀਮਤ (ਪ੍ਰਤੀ ਯੂਨਿਟ)',
    trend: 'ਰੁਝਾਨ',
    last_updated: 'ਆਖਰੀ ਵਾਰ ਅੱਪਡੇਟ ਕੀਤਾ ਗਿਆ',
    community_feed: 'ਭਾਈਚਾਰਕ ਫੀਡ',
    create_a_post: 'ਇੱਕ ਪੋਸਟ ਬਣਾਓ',
    whats_on_your_mind: 'ਤੁਹਾਡੇ ਮਨ ਵਿੱਚ ਕੀ ਹੈ, ਕਿਸਾਨ?',
    post_not_found: 'ਪੋਸਟ ਨਹੀਂ ਮਿਲੀ',
    back_to_community: 'ਭਾਈਚਾਰੇ ਤੇ ਵਾਪਸ ਜਾਓ',
    likes: 'ਪਸੰਦ',
    comments: 'ਟਿੱਪਣੀਆਂ',
    leave_a_comment: 'ਇੱਕ ਟਿੱਪਣੀ ਛੱਡੋ',
    write_your_comment: 'ਆਪਣੀ ਟਿੱਪਣੀ ਲਿਖੋ...',
    comment: 'ਟਿੱਪਣੀ',
    reply: 'ਜਵਾਬ',
    reply_to: 'ਨੂੰ ਜਵਾਬ ਦਿਓ',
    no_comments_yet: 'ਹਾਲੇ ਤੱਕ ਕੋਈ ਟਿੱਪਣੀ ਨਹੀਂ ਹੈ। ਟਿੱਪਣੀ ਕਰਨ ਵਾਲੇ ਪਹਿਲੇ ਬਣੋ!',
    login_to_post: 'ਲਾਗਇਨ ਦੀ ਲੋੜ ਹੈ',
    login_to_post_description: 'ਇੱਕ ਪੋਸਟ ਬਣਾਉਣ ਲਈ ਤੁਹਾਨੂੰ ਲਾਗਇਨ ਕਰਨਾ ਪਵੇਗਾ।',
    cannot_post_empty: 'ਪੋਸਟ ਦੀ ਸਮੱਗਰੀ ਖਾਲੀ ਨਹੀਂ ਹੋ ਸਕਦੀ।',
    post_created: 'ਪੋਸਟ ਸਫਲਤਾਪੂਰਵਕ ਬਣਾਇਆ ਗਿਆ!',
    error_creating_post: 'ਪੋਸਟ ਬਣਾਉਣ ਵਿੱਚ ਗਲਤੀ।',
    login_to_comment: 'ਲਾਗਇਨ ਦੀ ਲੋੜ ਹੈ',
    login_to_comment_desc: 'ਟਿੱਪਣੀ ਕਰਨ ਲਈ ਤੁਹਾਨੂੰ ਲਾਗਇਨ ਕਰਨਾ ਪਵੇਗਾ।',
    cannot_post_empty_comment: 'ਟਿੱਪਣੀ ਖਾਲੀ ਨਹੀਂ ਹੋ ਸਕਦੀ।',
    comment_posted: 'ਟਿੱਪਣੀ ਪੋਸਟ ਕੀਤੀ ਗਈ!',
    error_posting_comment: 'ਟਿੱਪਣੀ ਪੋਸਟ ਕਰਨ ਵਿੱਚ ਗਲਤੀ।',
    login_or_signup: 'ਲੌਗਇਨ ਜਾਂ ਸਾਈਨ ਅੱਪ ਕਰੋ',
    enter_mobile_for_otp: 'ਓਟੀਪੀ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਆਪਣਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ।',
    full_name: 'ਪੂਰਾ ਨਾਮ',
    enter_full_name: 'ਆਪਣਾ ਪੂਰਾ ਨਾਮ ਦਰਜ ਕਰੋ',
    mobile_number: 'ਮੋਬਾਈਲ ਨੰਬਰ',
    enter_mobile_number: 'ਆਪਣਾ 10-ਅੰਕਾਂ ਵਾਲਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ',
    send_otp: 'ਓਟੀਪੀ ਭੇਜੋ',
    my_profile: 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
    view_manage_account: 'ਆਪਣੇ ਖਾਤੇ ਦੇ ਵੇਰਵੇ ਵੇਖੋ ਅਤੇ ਪ੍ਰਬੰਧਿਤ ਕਰੋ।',
    name: 'ਨਾਮ',
    state: 'ਰਾਜ',
    select_state: 'ਆਪਣਾ ਰਾਜ ਚੁਣੋ',
    district: 'ਜ਼ਿਲ੍ਹਾ',
    select_district: 'ਆਪਣਾ ਜ਼ਿਲ੍ਹਾ ਚੁਣੋ',
    village_town: 'ਪਿੰਡ / ਸ਼ਹਿਰ',
    enter_village_town: 'ਆਪਣੇ ਪਿੰਡ ਜਾਂ ਸ਼ਹਿਰ ਦਾ ਨਾਮ ਦਰਜ ਕਰੋ',
    save_changes: 'ਤਬਦੀਲੀਆਂ ਨੂੰ ਸੰਭਾਲੋ',
    log_out: 'ਲੌਗ ਆਉਟ',
    profile_updated_title: 'ਪ੍ਰੋਫਾਈਲ ਅੱਪਡੇਟ ਕੀਤਾ ਗਿਆ',
    profile_updated_description: 'ਤੁਹਾਡਾ ਪ੍ਰੋਫਾਈਲ ਸਫਲਤਾਪੂਰਵਕ ਸੁਰੱਖਿਅਤ ਕੀਤਾ ਗਿਆ ਹੈ।',
    could_not_save_profile: 'ਪ੍ਰੋਫਾਈਲ ਨੂੰ ਸੁਰੱਖਿਅਤ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਿਆ।',
    login_failed: 'ਲੌਗਇਨ ਅਸਫਲ',
    login_failed_description: 'ਤੁਹਾਨੂੰ ਸਾਈਨ ਇਨ ਨਹੀਂ ਕੀਤਾ ਜਾ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    choose_language: 'ਐਪ ਲਈ ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ।',
    notifications: 'ਸੂਚਨਾਵਾਂ',
    enable_notifications: 'ਮਹੱਤਵਪੂਰਨ ਚੇਤਾਵਨੀਆਂ ਲਈ ਸੂਚਨਾਵਾਂ ਨੂੰ ਸਮਰੱਥ ਬਣਾਓ।',
    enable_notifications_button: 'ਸੂਚਨਾਵਾਂ ਨੂੰ ਸਮਰੱਥ ਬਣਾਓ',
    ai_farming_assistant: 'ਏਆਈ ਖੇਤੀਬਾੜੀ ਸਹਾਇਕ',
    ask_me_anything: 'ਖੇਤੀਬਾੜੀ ਬਾਰੇ ਮੈਨੂੰ ਕੁਝ ਵੀ ਪੁੱਛੋ!',
    ask_about_crops: 'ਫਸਲਾਂ, ਮਿੱਟੀ, ਜਾਂ ਕੀੜਿਆਂ ਬਾਰੇ ਪੁੱਛੋ...',
    assistant_can_mistake: 'ਕਿਸਾਨਏਆਈ ਗਲਤੀਆਂ ਕਰ ਸਕਦਾ ਹੈ। ਮਹੱਤਵਪੂਰਨ ਜਾਣਕਾਰੀ ਦੀ ਜਾਂਚ ਕਰਨ ਬਾਰੇ ਸੋਚੋ।',
    voice_assistant_title: 'ਆਵਾਜ਼ ਸਹਾਇਕ',
    listening: 'ਸੁਣ ਰਿਹਾ ਹਾਂ...',
    processing: 'ਪ੍ਰੋਸੈਸਿੰਗ ਹੋ ਰਹੀ ਹੈ...',
    ask_a_question: 'ਖੇਤੀਬਾੜੀ ਬਾਰੇ ਇੱਕ ਸਵਾਲ ਪੁੱਛੋ',
    plant_doctor_description: 'ਆਪਣੇ ਪੌਦੇ ਦੀ ਤਸਵੀਰ ਲਓ ਜਾਂ ਅੱਪਲੋਡ ਕਰੋ ਅਤੇ AI ਨਿਦਾਨ ਲਈ ਇੱਕ ਵੌਇਸ ਨੋਟ ਸ਼ਾਮਲ ਕਰੋ।',
    step_1_image: '1. ਇੱਕ ਚਿੱਤਰ ਪ੍ਰਦਾਨ ਕਰੋ',
    use_camera_or_upload: 'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਆਪਣੇ ਕੈਮਰੇ ਦੀ ਵਰਤੋਂ ਕਰੋ ਜਾਂ ਇੱਕ ਚਿੱਤਰ ਅੱਪਲੋਡ ਕਰੋ।',
    camera_access_denied_title: 'ਕੈਮਰਾ ਪਹੁੰਚ ਤੋਂ ਇਨਕਾਰ ਕੀਤਾ ਗਿਆ',
    camera_access_denied_description: 'ਇਸ ਵਿਸ਼ੇਸ਼ਤਾ ਦੀ ਵਰਤੋਂ ਕਰਨ ਲਈ ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੀਆਂ ਬ੍ਰਾਊਜ਼ਰ ਸੈਟਿੰਗਾਂ ਵਿੱਚ ਕੈਮਰਾ ਅਨੁਮਤੀਆਂ ਨੂੰ ਸਮਰੱਥ ਬਣਾਓ।',
    capture_photo: 'ਤਸਵੀਰ ਲਓ',
    use_camera: 'ਕੈਮਰਾ ਵਰਤੋ',
    upload_image: 'ਚਿੱਤਰ ਅੱਪਲੋਡ ਕਰੋ',
    step_2_voice_note: '2. ਇੱਕ ਵੌਇਸ ਨੋਟ ਸ਼ਾਮਲ ਕਰੋ (ਵਿਕਲਪਿਕ)',
    voice_note_placeholder: 'ਤੁਹਾਡਾ ਲਿਪੀਅੰਤਰਿਤ ਵੌਇਸ ਨੋਟ ਇੱਥੇ ਦਿਖਾਈ ਦੇਵੇਗਾ...',
    get_diagnosis: 'ਨਿਦਾਨ ਪ੍ਰਾਪਤ ਕਰੋ',
    diagnosing: 'ਨਿਦਾਨ ਕਰ ਰਿਹਾ ਹੈ...',
    new_diagnosis: 'ਨਵਾਂ ਨਿਦਾਨ ਸ਼ੁਰੂ ਕਰੋ',
    plant_diagnosis_report: 'ਪੌਦਾ ਨਿਦਾਨ ਰਿਪੋਰਟ',
    confidence: 'ਵਿਸ਼ਵਾਸ',
    quick_summary: 'ਤੁਰੰਤ ਸਾਰ',
    identification: 'ਪਛਾਣ',
    primary_species: 'ਮੁੱਖ ਪ੍ਰਜਾਤੀਆਂ',
    could_not_identify: 'ਪੌਦਿਆਂ ਦੀਆਂ ਪ੍ਰਜਾਤੀਆਂ ਦੀ ਪਛਾਣ ਨਹੀਂ ਕੀਤੀ ਜਾ ਸਕੀ।',
    diagnosis: 'ਨਿਦਾਨ',
    severity: 'ਗੰਭੀਰਤਾ',
    likelihood: 'ਸੰਭਾਵਨਾ',
    evidence: 'ਸਬੂਤ',
    no_issues_diagnosed: 'ਕੋਈ ਖਾਸ ਮੁੱਦੇ ਨਿਦਾਨ ਨਹੀਂ ਕੀਤੇ ਗਏ।',
    recommendations: 'ਸਿਫਾਰਸ਼ਾਂ',
    cultural_ipm: 'ਸੱਭਿਆਚਾਰਕ ਅਤੇ ਆਈਪੀਐਮ',
    organic_biological: 'ਜੈਵਿਕ/ਜੀਵ-ਵਿਗਿਆਨਕ',
    image_quality: 'ਚਿੱਤਰ ਦੀ ਗੁਣਵੱਤਾ',
    quality: 'ਗੁਣਵੱਤਾ',
    suggestions: 'ਸੁਝਾਅ',
    disease: 'ਬਿਮਾਰੀ',
    pest: 'ਕੀੜੇ',
    nutrient: 'ਪੋਸ਼ਕ ਤੱਤ',
    physiological: 'ਸਰੀਰਕ',
    camera_not_supported_title: 'ਕੈਮਰਾ ਸਮਰਥਿਤ ਨਹੀਂ ਹੈ',
    camera_not_supported_description: 'ਤੁਹਾਡਾ ਬ੍ਰਾਊਜ਼ਰ ਕੈਮਰਾ ਪਹੁੰਚ ਦਾ ਸਮਰਥਨ ਨਹੀਂ ਕਰਦਾ।',
    browser_not_supported_title: 'ਬ੍ਰਾਊਜ਼ਰ ਸਮਰਥਿਤ ਨਹੀਂ ਹੈ',
    browser_not_supported_description: 'ਤੁਹਾਡਾ ਬ੍ਰਾਊਜ਼ਰ ਆਵਾਜ਼ ਪਛਾਣ ਦਾ ਸਮਰਥਨ ਨਹੀਂ ਕਰਦਾ।',
    no_image_title: 'ਕੋਈ ਚਿੱਤਰ ਨਹੀਂ',
    no_image_description: 'ਕਿਰਪਾ ਕਰਕੇ ਪਹਿਲਾਂ ਇੱਕ ਚਿੱਤਰ ਪ੍ਰਦਾਨ ਕਰੋ।',
    diagnosis_failed_title: 'ਨਿਦਾਨ ਅਸਫਲ',
    diagnosis_failed_description: 'ਪੌਦੇ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰਦੇ ਸਮੇਂ ਇੱਕ ਗਲਤੀ ਆਈ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
  },
  gu: {
    welcome: 'પધારો',
    settings: 'સેટિંગ્સ',
    language: 'ભાષા',
    post: 'પોસ્ટ કરો',
    home: 'હોમ',
    ai_assistant: 'AI સહાયક',
    plant_doctor: 'પ્લાન્ટ ડોક્ટર',
    market: 'બજાર',
    community: 'સમુદાય',
    profile: 'પ્રોફાઇલ',
    welcome_to_kisanai: 'કિસાનએઆઈમાં આપનું સ્વાગત છે',
    welcome_message: 'નમસ્તે, {{name}}!',
    smart_farming_partner: 'એક સમૃદ્ધ પાક માટે તમારા સ્માર્ટ ખેતી ભાગીદાર.',
    quick_actions: 'ઝડપી ક્રિયાઓ',
    quick_links: 'ઝડપી લિંક્સ',
    get_farming_advice: 'ખેતીની સલાહ મેળવો',
    market_prices: 'બજાર ભાવ',
    check_crop_prices: 'પાકના ભાવ તપાસો',
    connect_with_farmers: 'ખેડૂતો સાથે જોડાઓ',
    customize_your_app: 'તમારી એપ્લિકેશનને કસ્ટમાઇઝ કરો',
    daily_tip: 'દૈનિક ટીપ',
    daily_tip_content: 'તમારા ખેતરોમાં સિંચાઈ કરતા પહેલા જમીનની ભેજ તપાસો. વધુ પડતું પાણી આપવું એ ઓછું પાણી આપવા જેટલું જ હાનિકારક હોઈ શકે છે.',
    voice_assistant: 'વૉઇસ સહાયક',
    current_weather: 'વર્તમાન હવામાન',
    weather_forecast: 'હવામાનની આગાહી',
    today: 'આજે',
    weather_error: 'હવામાન ભૂલ',
    humidity: 'ભેજ',
    wind: 'પવન',
    location_access_denied: 'સ્થાન ઍક્સેસ નકારી',
    fallback_location_weather: 'હવામાન માટે ડિફૉલ્ટ સ્થાન પર પાછા ફરી રહ્યા છીએ.',
    latest_prices: 'વિવિધ બજારોમાંથી નવીનતમ કૃષિ કોમોડિટીના ભાવ.',
    showing_markets_near: 'નજીકના બજારો બતાવી રહ્યું છે',
    crop: 'પાક',
    price_per_unit: 'કિંમત (એકમ દીઠ)',
    trend: 'વલણ',
    last_updated: 'છેલ્લે અપડેટ કર્યું',
    community_feed: 'સમુદાય ફીડ',
    create_a_post: 'એક પોસ્ટ બનાવો',
    whats_on_your_mind: 'તમારા મનમાં શું છે, ખેડૂત?',
    post_not_found: 'પોસ્ટ મળી નથી',
    back_to_community: 'સમુદાય પર પાછા જાઓ',
    likes: 'પસંદ',
    comments: 'ટિપ્પણીઓ',
    leave_a_comment: 'એક ટિપ્પણી મૂકો',
    write_your_comment: 'તમારી ટિપ્પણી લખો...',
    comment: 'ટિપ્પણી',
    reply: 'જવાબ',
    reply_to: 'ને જવાબ આપો',
    no_comments_yet: 'હજુ સુધી કોઈ ટિપ્પણીઓ નથી. ટિપ્પણી કરનાર પ્રથમ બનો!',
    login_to_post: 'લૉગિન જરૂરી છે',
    login_to_post_description: 'એક પોસ્ટ બનાવવા માટે તમારે લૉગિન કરવું પડશે.',
    cannot_post_empty: 'પોસ્ટની સામગ્રી ખાલી ન હોઈ શકે.',
    post_created: 'પોસ્ટ સફળતાપૂર્વક બનાવવામાં આવી!',
    error_creating_post: 'પોસ્ટ બનાવતી વખતે ભૂલ.',
    login_to_comment: 'લૉગિન જરૂરી છે',
    login_to_comment_desc: 'ટિપ્પણી કરવા માટે તમારે લૉગિન કરવું પડશે.',
    cannot_post_empty_comment: 'ટિપ્પણી ખાલી ન હોઈ શકે.',
    comment_posted: 'ટિપ્પણી પોસ્ટ થઈ!',
    error_posting_comment: 'ટિપ્પણી પોસ્ટ કરતી વખતે ભૂલ.',
    login_or_signup: 'લૉગિન અથવા સાઇન અપ કરો',
    enter_mobile_for_otp: 'OTP મેળવવા માટે તમારો મોબાઇલ નંબર દાખલ કરો.',
    full_name: 'પૂરું નામ',
    enter_full_name: 'તમારું પૂરું નામ દાખલ કરો',
    mobile_number: 'મોબાઇલ નંબર',
    enter_mobile_number: 'તમારો 10-અંકનો મોબાઇલ નંબર દાખલ કરો',
    send_otp: 'OTP મોકલો',
    my_profile: 'મારી પ્રોફાઇલ',
    view_manage_account: 'તમારા એકાઉન્ટની વિગતો જુઓ અને મેનેજ કરો.',
    name: 'નામ',
    state: 'રાજ્ય',
    select_state: 'તમારું રાજ્ય પસંદ કરો',
    district: 'જિલ્લો',
    select_district: 'તમારો જિલ્લો પસંદ કરો',
    village_town: 'ગામ / શહેર',
    enter_village_town: 'તમારા ગામ અથવા શહેરનું નામ દાખલ કરો',
    save_changes: 'ફેરફારો સાચવો',
    log_out: 'લૉગ આઉટ',
    profile_updated_title: 'પ્રોફાઇલ અપડેટ થઈ',
    profile_updated_description: 'તમારી પ્રોફાઇલ સફળતાપૂર્વક સાચવવામાં આવી છે.',
    could_not_save_profile: 'પ્રોફાઇલ સાચવી શકાયું નથી.',
    login_failed: 'લૉગિન નિષ્ફળ',
    login_failed_description: 'તમને સાઇન ઇન કરી શકાયું નથી. કૃપા કરીને ફરી પ્રયાસ કરો.',
    choose_language: 'એપ્લિકેશન માટે તમારી પસંદગીની ભાષા પસંદ કરો.',
    notifications: 'સૂચનાઓ',
    enable_notifications: 'મહત્વપૂર્ણ ચેતવણીઓ માટે સૂચનાઓ સક્ષમ કરો.',
    enable_notifications_button: 'સૂચનાઓ સક્ષમ કરો',
    ai_farming_assistant: 'AI ખેતી સહાયક',
    ask_me_anything: 'ખેતી વિશે મને કંઈપણ પૂછો!',
    ask_about_crops: 'પાક, જમીન અથવા જીવાતો વિશે પૂછો...',
    assistant_can_mistake: 'કિસાનએઆઈ ભૂલો કરી શકે છે. મહત્વપૂર્ણ માહિતી તપાસવાનું વિચારો.',
    voice_assistant_title: 'વૉઇસ સહાયક',
    listening: 'સાંભળી રહ્યું છે...',
    processing: 'પ્રક્રિયા કરી રહ્યું છે...',
    ask_a_question: 'ખેતી વિશે એક પ્રશ્ન પૂછો',
    plant_doctor_description: 'તમારા છોડનો ફોટો પાડો અથવા અપલોડ કરો અને AI નિદાન માટે વૉઇસ નોટ ઉમેરો.',
    step_1_image: '૧. એક છબી પ્રદાન કરો',
    use_camera_or_upload: 'શરૂ કરવા માટે તમારા કૅમેરાનો ઉપયોગ કરો અથવા એક છબી અપલોડ કરો.',
    camera_access_denied_title: 'કૅમેરા ઍક્સેસ નકારી',
    camera_access_denied_description: 'આ સુવિધાનો ઉપયોગ કરવા માટે કૃપા કરીને તમારા બ્રાઉઝર સેટિંગ્સમાં કૅમેરા પરવાનગીઓ સક્ષમ કરો.',
    capture_photo: 'ફોટો પાડો',
    use_camera: 'કૅમેરાનો ઉપયોગ કરો',
    upload_image: 'છબી અપલોડ કરો',
    step_2_voice_note: '૨. વૉઇસ નોટ ઉમેરો (વૈકલ્પિક)',
    voice_note_placeholder: 'તમારી લિવ્યંતરિત વૉઇસ નોટ અહીં દેખાશે...',
    get_diagnosis: 'નિદાન મેળવો',
    diagnosing: 'નિદાન કરી રહ્યું છે...',
    new_diagnosis: 'નવું નિદાન શરૂ કરો',
    plant_diagnosis_report: 'છોડ નિદાન અહેવાલ',
    confidence: 'આત્મવિશ્વાસ',
    quick_summary: 'ઝડપી સારાંશ',
    identification: 'ઓળખ',
    primary_species: 'પ્રાથમિક પ્રજાતિઓ',
    could_not_identify: 'છોડની પ્રજાતિઓ ઓળખી શકાઈ નથી.',
    diagnosis: 'નિદાન',
    severity: 'ગંભીરતા',
    likelihood: 'સંભાવના',
    evidence: 'પુરાવા',
    no_issues_diagnosed: 'કોઈ ચોક્કસ સમસ્યાઓનું નિદાન થયું નથી.',
    recommendations: 'ભલામણો',
    cultural_ipm: 'સાંસ્કૃતિક અને IPM',
    organic_biological: 'કાર્બનિક/જૈવિક',
    image_quality: 'છબી ગુણવત્તા',
    quality: 'ગુણવત્તા',
    suggestions: 'સૂચનો',
    disease: 'રોગ',
    pest: 'જીવાત',
    nutrient: 'પોષક તત્ત્વો',
    physiological: 'શારીરિક',
    camera_not_supported_title: 'કૅમેરા સપોર્ટેડ નથી',
    camera_not_supported_description: 'તમારું બ્રાઉઝર કૅમેરા ઍક્સેસને સપોર્ટ કરતું નથી.',
    browser_not_supported_title: 'બ્રાઉઝર સપોર્ટેડ નથી',
    browser_not_supported_description: 'તમારું બ્રાઉઝર વૉઇસ રેકગ્નિશનને સપોર્ટ કરતું નથી.',
    no_image_title: 'કોઈ છબી નથી',
    no_image_description: 'કૃપા કરીને પહેલા એક છબી પ્રદાન કરો.',
    diagnosis_failed_title: 'નિદાન નિષ્ફળ',
    diagnosis_failed_description: 'છોડનું વિશ્લેષણ કરતી વખતે એક ભૂલ આવી. કૃપા કરીને ફરી પ્રયાસ કરો.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');
  
  const t = (key: string, values: {[key: string]: string | number} = {}): string => {
    const translationSet = translations[language] || translations.en;
    let translation = translationSet[key as keyof typeof translationSet] || key;
    
    Object.keys(values).forEach(k => {
        translation = translation.replace(`{{${k}}}`, String(values[k]));
    });

    return translation;
  };
  
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
